
import type { Chemical } from './types';

export const CHEMICAL_LIBRARY: Chemical[] = [
  {
    id: '1',
    name: 'Sodium',
    formula: 'Na',
    naturalState: 'solid',
    color: '#cbd5e1',
    molecularWeight: 22.99,
    density: 0.97,
    solubility: 0,
    allowsLiquidView: false,
    description: 'Sodium is a soft, silvery-white, highly reactive alkali metal. It is so soft that it can be easily cut with a knife. Due to its extreme reactivity with air and water, it must be stored under mineral oil or an inert gas.'
  },
  {
    id: '2',
    name: 'Potassium',
    formula: 'K',
    naturalState: 'solid',
    color: '#94a3b8',
    molecularWeight: 39.10,
    density: 0.86,
    solubility: 0,
    allowsLiquidView: false,
    description: 'Potassium is a soft silvery-white alkali metal that oxidizes rapidly in air and reacts vigorously with water. It is essential for cell function in all living organisms.'
  },
  {
    id: '3',
    name: 'Copper Sulfate',
    formula: 'CuSO₄',
    naturalState: 'powder',
    color: '#3b82f6',
    molecularWeight: 159.61,
    density: 3.6,
    solubility: 32,
    allowsLiquidView: true,
    description: 'Copper(II) sulfate is a bright blue salt. It is widely used in agriculture as a fungicide and in laboratories to demonstrate hydrated and anhydrous crystal forms.'
  },
  {
    id: '4',
    name: 'Sodium Chloride',
    formula: 'NaCl',
    naturalState: 'powder',
    color: '#ffffff',
    molecularWeight: 58.44,
    density: 2.16,
    solubility: 36,
    allowsLiquidView: true,
    description: 'Commonly known as table salt, sodium chloride is an ionic compound. It forms cubic crystals and is highly soluble in water, forming a clear electrolyte solution.'
  },
  {
    id: '5',
    name: 'Hydrochloric Acid',
    formula: 'HCl',
    naturalState: 'liquid',
    color: '#e2e8f0',
    molecularWeight: 36.46,
    density: 1.18,
    solubility: 100,
    allowsLiquidView: true,
    description: 'A strong, corrosive acid that is a primary component of gastric acid. In the lab, it is usually handled as an aqueous solution.'
  },
  {
    id: '6',
    name: 'Chlorine',
    formula: 'Cl₂',
    naturalState: 'gas',
    color: '#facc15',
    molecularWeight: 70.90,
    density: 0.0032,
    solubility: 0.7,
    allowsLiquidView: true,
    description: 'Chlorine is a pale yellow-green gas with a suffocating odor. It is a powerful oxidizing agent and is highly toxic if inhaled.'
  },
  {
    id: '7',
    name: 'Lithium',
    formula: 'Li',
    naturalState: 'solid',
    color: '#e2e8f0',
    molecularWeight: 6.94,
    density: 0.53,
    solubility: 0,
    allowsLiquidView: false,
    description: 'Lithium metal is usually found in the form of small pieces or thin wire. As an alkali metal, lithium is soft and can be cut with a knife. It is highly reactive and is typically stored under mineral oil.'
  },
  {
    id: '8',
    name: 'Fluorine',
    formula: 'F₂',
    naturalState: 'gas',
    color: '#fef3c7',
    molecularWeight: 38.00,
    density: 0.0017,
    solubility: 0,
    allowsLiquidView: false,
    description: 'Fluorine is a pale yellow, highly reactive gas. It is extremely toxic and must be handled in sealed systems made from special materials.'
  },
  {
    id: '9',
    name: 'Potassium Permanganate',
    formula: 'KMnO₄',
    naturalState: 'powder',
    color: '#7e22ce',
    molecularWeight: 158.03,
    density: 2.7,
    solubility: 6.4,
    allowsLiquidView: true,
    description: 'Deep purple crystalline salt. It is a strong oxidizing agent used in chemical analysis and as a disinfectant.'
  },
  {
    id: '10',
    name: 'Ammonia',
    formula: 'NH₃',
    naturalState: 'gas',
    color: '#dcfce7',
    molecularWeight: 17.03,
    density: 0.0007,
    solubility: 47,
    allowsLiquidView: true,
    description: 'A colorless gas with a characteristic pungent smell. It is used extensively as a fertilizer and in industrial cooling.'
  },
  {
    id: '11',
    name: 'Mercury',
    formula: 'Hg',
    naturalState: 'liquid',
    color: '#64748b',
    molecularWeight: 200.59,
    density: 13.53,
    solubility: 0,
    allowsLiquidView: false,
    description: 'A heavy, silvery d-block element, mercury is the only metallic element that is liquid at standard conditions for temperature and pressure.'
  },
  {
    id: '12',
    name: 'Bromine',
    formula: 'Br₂',
    naturalState: 'liquid',
    color: '#991b1b',
    molecularWeight: 159.81,
    density: 3.10,
    solubility: 3.5,
    allowsLiquidView: true,
    description: 'A fuming red-brown liquid at room temperature that evaporates readily to form a similarly colored gas. It is the only nonmetallic element that is liquid at standard conditions.'
  },
  {
    id: '13',
    name: 'Iodine',
    formula: 'I₂',
    naturalState: 'solid',
    color: '#1e1b4b',
    molecularWeight: 253.81,
    density: 4.93,
    solubility: 0.03,
    allowsLiquidView: true,
    description: 'A lustrous, purple-black solid that sublimes at standard temperatures into a violet gas. It is an essential trace element for humans.'
  },
  {
    id: '14',
    name: 'Sulfuric Acid',
    formula: 'H₂SO₄',
    naturalState: 'liquid',
    color: '#f1f5f9',
    molecularWeight: 98.08,
    density: 1.83,
    solubility: 100,
    allowsLiquidView: true,
    description: 'A highly corrosive strong mineral acid. It is colorless to slightly yellow and has a pungent odor.'
  },
  {
    id: '15',
    name: 'Ethanol',
    formula: 'C₂H₅OH',
    naturalState: 'liquid',
    color: '#f8fafc',
    molecularWeight: 46.07,
    density: 0.78,
    solubility: 100,
    allowsLiquidView: true,
    description: 'A volatile, flammable, colorless liquid with a characteristic odor. It is widely used as a solvent and in fuel.'
  },
  {
    id: '16',
    name: 'Methane',
    formula: 'CH₄',
    naturalState: 'gas',
    color: '#f8fafc',
    molecularWeight: 16.04,
    density: 0.0006,
    solubility: 0.002,
    allowsLiquidView: false,
    description: 'The simplest alkane and the main component of natural gas. It is colorless and odorless.'
  },
  {
    id: '17',
    name: 'Carbon Dioxide',
    formula: 'CO₂',
    naturalState: 'gas',
    color: '#f8fafc',
    molecularWeight: 44.01,
    density: 0.0019,
    solubility: 0.14,
    allowsLiquidView: true,
    description: 'A colorless gas that is vital to life on Earth. In the lab, it is often generated by reacting carbonates with acids.'
  },
  {
    id: '18',
    name: 'Iron',
    formula: 'Fe',
    naturalState: 'solid',
    color: '#475569',
    molecularWeight: 55.85,
    density: 7.87,
    solubility: 0,
    allowsLiquidView: false,
    description: 'A lustrous, ductile, malleable, silver-gray metal. It is known to exist in four distinct crystalline forms.'
  },
  {
    id: '19',
    name: 'Magnesium',
    formula: 'Mg',
    naturalState: 'solid',
    color: '#94a3b8',
    molecularWeight: 24.31,
    density: 1.74,
    solubility: 0,
    allowsLiquidView: false,
    description: 'A shiny gray solid which bears a close physical resemblance to the other five elements in the second column of the periodic table.'
  },
  {
    id: '20',
    name: 'Gold',
    formula: 'Au',
    naturalState: 'solid',
    color: '#fbbf24',
    molecularWeight: 196.97,
    density: 19.3,
    solubility: 0,
    allowsLiquidView: false,
    description: 'A transition metal and a group 11 element. It is one of the least reactive chemical elements and is solid under standard conditions.'
  },
  {
    id: '21',
    name: 'Oxygen',
    formula: 'O₂',
    naturalState: 'gas',
    color: '#bfdbfe',
    molecularWeight: 32.00,
    density: 0.0014,
    solubility: 0.004,
    allowsLiquidView: false,
    description: 'A colorless, odorless, tasteless gas essential to living organisms.'
  },
  {
    id: '22',
    name: 'Nitrogen',
    formula: 'N₂',
    naturalState: 'gas',
    color: '#e0f2fe',
    molecularWeight: 28.01,
    density: 0.0012,
    solubility: 0.002,
    allowsLiquidView: false,
    description: 'A chemical element that is a colorless, odorless, tasteless gas at standard conditions.'
  },
  {
    id: '23',
    name: 'Argon',
    formula: 'Ar',
    naturalState: 'gas',
    color: '#e2e8f0',
    molecularWeight: 39.95,
    density: 0.0017,
    solubility: 0.003,
    allowsLiquidView: false,
    description: 'A noble gas that is colorless, odorless, tasteless and non-toxic.'
  },
  {
    id: '24',
    name: 'Xenon',
    formula: 'Xe',
    naturalState: 'plasma',
    color: '#a5b4fc',
    molecularWeight: 131.29,
    density: 0.0058,
    solubility: 0,
    allowsLiquidView: false,
    description: 'A dense, colorless, odorless noble gas found in Earth\'s atmosphere in trace amounts.'
  },
  {
    id: '25',
    name: 'Silver Nitrate',
    formula: 'AgNO₃',
    naturalState: 'powder',
    color: '#f8fafc',
    molecularWeight: 169.87,
    density: 4.35,
    solubility: 216,
    allowsLiquidView: true,
    description: 'An inorganic compound with formula AgNO3. This salt is a versatile precursor to many other silver compounds.'
  },
  {
    id: '26',
    name: 'Barium Chloride',
    formula: 'BaCl₂',
    naturalState: 'powder',
    color: '#ffffff',
    molecularWeight: 208.23,
    density: 3.85,
    solubility: 35.8,
    allowsLiquidView: true,
    description: 'An inorganic salt that is one of the most common water-soluble salts of barium.'
  },
  {
    id: '27',
    name: 'Cobalt(II) Chloride',
    formula: 'CoCl₂',
    naturalState: 'powder',
    color: '#ec4899',
    molecularWeight: 129.84,
    density: 3.35,
    solubility: 45,
    allowsLiquidView: true,
    description: 'An inorganic compound of cobalt and chlorine. It is most commonly found as the deep blue anhydrous form.'
  },
  {
    id: '28',
    name: 'Nickel(II) Sulfate',
    formula: 'NiSO₄',
    naturalState: 'powder',
    color: '#10b981',
    molecularWeight: 154.75,
    density: 3.68,
    solubility: 38,
    allowsLiquidView: true,
    description: 'Usually refers to the inorganic compound with the formula NiSO4(H2O)6. This highly soluble blue-green salt is a common source of the Ni2+ ion.'
  },
  {
    id: '29',
    name: 'Potassium Dichromate',
    formula: 'K₂Cr₂O₇',
    naturalState: 'powder',
    color: '#f97316',
    molecularWeight: 294.18,
    density: 2.67,
    solubility: 12,
    allowsLiquidView: true,
    description: 'A common inorganic chemical reagent, most commonly used as an oxidizing agent in various laboratory and industrial applications.'
  },
  {
    id: '30',
    name: 'Glucose',
    formula: 'C₆H₁₂O₆',
    naturalState: 'powder',
    color: '#f8fafc',
    molecularWeight: 180.16,
    density: 1.54,
    solubility: 91,
    allowsLiquidView: true,
    description: 'A simple sugar with the molecular formula C6H12O6. It is the most abundant monosaccharide.'
  },
  {
    id: '31',
    name: 'Sucrose',
    formula: 'C₁₂H₂₂O₁₁',
    naturalState: 'powder',
    color: '#ffffff',
    molecularWeight: 342.30,
    density: 1.58,
    solubility: 200,
    allowsLiquidView: true,
    description: 'Common sugar. It is a disaccharide, a molecule composed of two monosaccharides: glucose and fructose.'
  },
  {
    id: '32',
    name: 'Glycerin',
    formula: 'C₃H₈O₃',
    naturalState: 'liquid',
    color: '#f8fafc',
    molecularWeight: 92.09,
    density: 1.26,
    solubility: 100,
    allowsLiquidView: true,
    description: 'A simple polyol compound. It is a colorless, odorless, viscous liquid that is sweet-tasting and non-toxic.'
  },
  {
    id: '33',
    name: 'Acetone',
    formula: 'C₃H₆O',
    naturalState: 'liquid',
    color: '#f1f5f9',
    molecularWeight: 58.08,
    density: 0.79,
    solubility: 100,
    allowsLiquidView: true,
    description: 'The simplest and smallest ketone. It is a colorless, highly volatile and flammable liquid with a characteristic pungent odor.'
  },
  {
    id: '34',
    name: 'Sulfur',
    formula: 'S₈',
    naturalState: 'powder',
    color: '#facc15',
    molecularWeight: 256.52,
    density: 2.07,
    solubility: 0,
    allowsLiquidView: false,
    description: 'A bright yellow, crystalline solid at room temperature. It is a nonmetal.'
  },
  {
    id: '35',
    name: 'Acetic Acid',
    formula: 'CH₃COOH',
    naturalState: 'liquid',
    color: '#f8fafc',
    molecularWeight: 60.05,
    density: 1.05,
    solubility: 100,
    allowsLiquidView: true,
    description: 'A colorless liquid organic compound. It has a distinctive sour taste and pungent smell.'
  },
  {
    id: '36',
    name: 'Hydrogen Peroxide',
    formula: 'H₂O₂',
    naturalState: 'liquid',
    color: '#eff6ff',
    molecularWeight: 34.01,
    density: 1.45,
    solubility: 100,
    allowsLiquidView: true,
    description: 'A chemical compound with the formula H2O2. In its pure form, it is a very pale blue liquid, slightly more viscous than water.'
  },
  {
    id: '37',
    name: 'Calcium Carbonate',
    formula: 'CaCO₃',
    naturalState: 'powder',
    color: '#f3f4f6',
    molecularWeight: 100.09,
    density: 2.71,
    solubility: 0.001,
    allowsLiquidView: true,
    description: 'A common substance found in rocks and is the main component of shells of marine organisms, snails, coal balls, pearls, and eggshells.'
  },
  {
    id: '38',
    name: 'Zinc Sulfate',
    formula: 'ZnSO₄',
    naturalState: 'powder',
    color: '#ffffff',
    molecularWeight: 161.47,
    density: 3.54,
    solubility: 57,
    allowsLiquidView: true,
    description: 'An inorganic compound. It is a colorless solid that is commonly encountered as the heptahydrate ZnSO4(H2O)7.'
  },
  {
    id: '39',
    name: 'Ammonium Nitrate',
    formula: 'NH₄NO₃',
    naturalState: 'powder',
    color: '#ffffff',
    molecularWeight: 80.04,
    density: 1.72,
    solubility: 150,
    allowsLiquidView: true,
    description: 'A white crystalline salt consisting of ions of ammonium and nitrate. It is highly soluble in water.'
  },
  {
    id: '40',
    name: 'Neon',
    formula: 'Ne',
    naturalState: 'gas',
    color: '#fee2e2',
    molecularWeight: 20.18,
    density: 0.0009,
    solubility: 0.001,
    allowsLiquidView: false,
    description: 'A noble gas. Neon is a colorless, odorless, inert monatomic gas under standard conditions.'
  },
  {
    id: '41',
    name: 'Helium',
    formula: 'He',
    naturalState: 'gas',
    color: '#f8fafc',
    molecularWeight: 4.00,
    density: 0.00018,
    solubility: 0.0001,
    allowsLiquidView: false,
    description: 'A colorless, odorless, tasteless, non-toxic, inert, monatomic gas, the first in the noble gas group.'
  },
  {
    id: '42',
    name: 'Lead(II) Nitrate',
    formula: 'Pb(NO₃)₂',
    naturalState: 'powder',
    color: '#ffffff',
    molecularWeight: 331.20,
    density: 4.53,
    solubility: 52,
    allowsLiquidView: true,
    description: 'An inorganic compound with the chemical formula Pb(NO3)2. It commonly occurs as a colorless crystal or white powder.'
  },
  {
    id: '43',
    name: 'Manganese(II) Sulfate',
    formula: 'MnSO₄',
    naturalState: 'powder',
    color: '#fbcfe8',
    molecularWeight: 151.00,
    density: 3.25,
    solubility: 52,
    allowsLiquidView: true,
    description: 'An inorganic compound with the formula MnSO4. This pale pink deliquescent solid is a commercially significant manganese(II) salt.'
  },
  {
    id: '44',
    name: 'Copper(II) Chloride',
    formula: 'CuCl₂',
    naturalState: 'powder',
    color: '#0d9488',
    molecularWeight: 134.45,
    density: 3.39,
    solubility: 70,
    allowsLiquidView: true,
    description: 'An inorganic compound. The anhydrous form is a yellowish-brown powder, but it most commonly exists as a blue-green dihydrate.'
  },
  {
    id: '45',
    name: 'Ferrous Sulfate',
    formula: 'FeSO₄',
    naturalState: 'powder',
    color: '#4ade80',
    molecularWeight: 151.91,
    density: 2.84,
    solubility: 26,
    allowsLiquidView: true,
    description: 'Denotes a range of salts with the formula FeSO4·xH2O. These compounds exist most commonly as the heptahydrate.'
  },
  {
    id: '46',
    name: 'Calcium Chloride',
    formula: 'CaCl₂',
    naturalState: 'powder',
    color: '#ffffff',
    molecularWeight: 110.98,
    density: 2.15,
    solubility: 74,
    allowsLiquidView: true,
    description: 'An inorganic compound, a salt with the chemical formula CaCl2. It is a white colored crystalline solid at room temperature.'
  },
  {
    id: '47',
    name: 'Potassium Iodide',
    formula: 'KI',
    naturalState: 'powder',
    color: '#ffffff',
    molecularWeight: 166.00,
    density: 3.12,
    solubility: 140,
    allowsLiquidView: true,
    description: 'A chemical compound, medication, and dietary supplement. It is an ionic compound.'
  },
  {
    id: '48',
    name: 'Phosphorus (White)',
    formula: 'P₄',
    naturalState: 'solid',
    color: '#fef3c7',
    molecularWeight: 123.90,
    density: 1.82,
    solubility: 0,
    allowsLiquidView: false,
    description: 'A soft, waxy, yellow-white solid with a garlic-like odor. It is highly reactive and spontaneous in air.'
  },
  {
    id: '49',
    name: 'Nitric Acid',
    formula: 'HNO₃',
    naturalState: 'liquid',
    color: '#fef3c7',
    molecularWeight: 63.01,
    density: 1.51,
    solubility: 100,
    allowsLiquidView: true,
    description: 'A highly corrosive mineral acid. The pure compound is colorless, but older samples tend to acquire a yellow cast.'
  },
  {
    id: '50',
    name: 'Benzene',
    formula: 'C₆H₆',
    naturalState: 'liquid',
    color: '#f8fafc',
    molecularWeight: 78.11,
    density: 0.87,
    solubility: 0.18,
    allowsLiquidView: true,
    description: 'An organic chemical compound with the molecular formula C6H6. The benzene molecule is composed of six carbon atoms joined in a planar ring.'
  },
  {
    id: '51',
    name: 'Argon',
    formula: 'Ar',
    naturalState: 'gas',
    color: '#e2e8f0',
    molecularWeight: 39.95,
    density: 0.0017,
    solubility: 0.003,
    allowsLiquidView: false,
    description: 'A noble gas, the third-most abundant gas in Earth\'s atmosphere.'
  },
  {
    id: '52',
    name: 'Sodium Hydroxide',
    formula: 'NaOH',
    naturalState: 'powder',
    color: '#ffffff',
    molecularWeight: 40.00,
    density: 2.13,
    solubility: 109,
    allowsLiquidView: true,
    description: 'Also known as lye and caustic soda, it is an inorganic compound. It is a white solid ionic compound.'
  }
];
