/**
 * Virtual Chemistry Lab — Complete Element Seed Data
 * All 118 elements with realistic scientific values
 * Sources: IUPAC, NIST, WebElements, Royal Society of Chemistry
 */

export const elementsSeed = [
  // ─── Period 1 ─────────────────────────────────────────────
  {
    atomic_number: 1,
    name: "Hydrogen",
    symbol: "H",
    latin_name: "Hydrogenium",
    period: 1,
    group: 1,
    block: "s",
    category: "reactive nonmetal",
    phase_at_stp: "gas",
    standard_state_color: "colorless",
    atomic_mass: 1.008,
    density_g_cm3: 0.00008988,
    valency: [1],
    oxidation_states: [-1, 1],
    common_oxidation_state: 1,
    electronic_configuration: {
      full: "1s¹",
      shorthand: "1s¹",
      noble_gas_core: null,
      valence_electrons: 1,
      electron_shells: [1],
    },
    radii: { atomic: 53, covalent: 31, van_der_waals: 120, ionic: null },
    thermodynamics: {
      melting_point_k: 14.01,
      boiling_point_k: 20.28,
      heat_of_fusion_kj_mol: 0.117,
      heat_of_vaporization_kj_mol: 0.904,
      specific_heat_j_gk: 14.304,
      thermal_conductivity_w_mk: 0.1805,
    },
    electrical: {
      electronegativity_pauling: 2.2,
      ionization_energies_kj_mol: [1312.0],
      electron_affinity_kj_mol: 72.8,
      electrical_conductivity_s_m: null,
      magnetic_type: "diamagnetic",
    },
    abundance: {
      earth_crust_ppm: 1400,
      ocean_ppm: 108000,
      universe_ppm: 739000,
      human_body_ppm: 100000,
    },
    isotopes: [
      { mass_number: 1, natural_abundance_percent: 99.9855, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 2, natural_abundance_percent: 0.0145, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 3, natural_abundance_percent: 0, half_life: "12.32 yr", decay_mode: "β−", is_stable: false },
    ],
    radioactive: false,
    stability: "stable",
    discovery: {
      discoverer: "Henry Cavendish",
      year: 1766,
      location: "England",
      named_after: "Greek: hydro (water) + genes (forming)",
      etymology: "Water-forming",
    },
    cas_number: "1333-74-0",
    description: "The lightest and most abundant element in the universe, constituting about 75% of all normal matter by mass.",
    detailed_description: "Hydrogen is the first element on the periodic table and the most abundant element in the universe. In its elemental form it exists as a diatomic gas (H₂) that is colorless, odorless, and highly flammable. It plays a crucial role as a fuel source and in chemical synthesis. Hydrogen is central to the structure of water, organic compounds, and living organisms.",
    toxicity_level: "none",
    hazard_codes: ["GHS02", "GHS04"],
  },
  {
    atomic_number: 2,
    name: "Helium",
    symbol: "He",
    latin_name: "Helium",
    period: 1,
    group: 18,
    block: "s",
    category: "noble gas",
    phase_at_stp: "gas",
    standard_state_color: "colorless",
    atomic_mass: 4.0026,
    density_g_cm3: 0.0001785,
    valency: [0],
    oxidation_states: [0],
    common_oxidation_state: 0,
    electronic_configuration: {
      full: "1s²",
      shorthand: "1s²",
      noble_gas_core: null,
      valence_electrons: 2,
      electron_shells: [2],
    },
    radii: { atomic: 31, covalent: 28, van_der_waals: 140, ionic: null },
    thermodynamics: {
      melting_point_k: null,
      boiling_point_k: 4.22,
      heat_of_fusion_kj_mol: null,
      heat_of_vaporization_kj_mol: 0.0829,
      specific_heat_j_gk: 5.193,
      thermal_conductivity_w_mk: 0.1513,
    },
    electrical: {
      electronegativity_pauling: null,
      ionization_energies_kj_mol: [2372.3, 5250.5],
      electron_affinity_kj_mol: 0,
      electrical_conductivity_s_m: null,
      magnetic_type: "diamagnetic",
    },
    abundance: {
      earth_crust_ppm: 0.008,
      ocean_ppm: 0.00007,
      universe_ppm: 240000,
      human_body_ppm: null,
    },
    isotopes: [
      { mass_number: 3, natural_abundance_percent: 0.0002, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 4, natural_abundance_percent: 99.9998, half_life: "stable", decay_mode: null, is_stable: true },
    ],
    radioactive: false,
    stability: "stable",
    discovery: {
      discoverer: "Pierre Janssen / Norman Lockyer",
      year: 1868,
      location: "India / England",
      named_after: "Helios — Greek sun god",
      etymology: "First observed in the solar spectrum",
    },
    cas_number: "7440-59-7",
    description: "The second lightest element and second most abundant in the universe, a noble gas that remains liquid even at near absolute zero under standard pressure.",
    detailed_description: "Helium is an inert, colorless, odorless, non-toxic noble gas. It has the lowest boiling point of any element and is the only element that cannot be solidified at atmospheric pressure. Discovered through spectroscopy of the Sun before being isolated on Earth, helium is used in cryogenics, as a lifting gas, and as an inert atmosphere in various industrial processes.",
    toxicity_level: "none",
    hazard_codes: ["GHS04"],
  },
  // ─── Period 2 ─────────────────────────────────────────────
  {
    atomic_number: 3,
    name: "Lithium",
    symbol: "Li",
    latin_name: "Lithium",
    period: 2,
    group: 1,
    block: "s",
    category: "alkali metal",
    phase_at_stp: "solid",
    standard_state_color: "silvery-white",
    atomic_mass: 6.94,
    density_g_cm3: 0.534,
    valency: [1],
    oxidation_states: [1],
    common_oxidation_state: 1,
    electronic_configuration: {
      full: "1s² 2s¹",
      shorthand: "[He] 2s¹",
      noble_gas_core: "He",
      valence_electrons: 1,
      electron_shells: [2, 1],
    },
    radii: { atomic: 167, covalent: 128, van_der_waals: 182, ionic: 76 },
    thermodynamics: {
      melting_point_k: 453.65,
      boiling_point_k: 1615,
      heat_of_fusion_kj_mol: 3,
      heat_of_vaporization_kj_mol: 136,
      specific_heat_j_gk: 3.582,
      thermal_conductivity_w_mk: 84.8,
    },
    electrical: {
      electronegativity_pauling: 0.98,
      ionization_energies_kj_mol: [520.2, 7298.1, 11815],
      electron_affinity_kj_mol: 59.6,
      electrical_conductivity_s_m: 1.08e7,
      magnetic_type: "diamagnetic",
    },
    abundance: {
      earth_crust_ppm: 20,
      ocean_ppm: 0.17,
      universe_ppm: 6,
      human_body_ppm: 0.03,
    },
    isotopes: [
      { mass_number: 6, natural_abundance_percent: 7.59, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 7, natural_abundance_percent: 92.41, half_life: "stable", decay_mode: null, is_stable: true },
    ],
    radioactive: false,
    stability: "stable",
    discovery: {
      discoverer: "Johan August Arfwedson",
      year: 1817,
      location: "Sweden",
      named_after: "Greek: lithos (stone)",
      etymology: "Discovered in petalite ore",
    },
    cas_number: "7439-93-2",
    description: "The lightest metal and the lightest solid element, essential for modern rechargeable batteries and mood-stabilizing medications.",
    detailed_description: "Lithium is a soft, silvery-white alkali metal. It is the lightest metal and the least dense solid element. Highly reactive with water and air, it must be stored under mineral oil. Lithium's greatest modern importance is as the key component in lithium-ion batteries. It also plays a role in psychiatric medicine and has applications in nuclear physics and as a heat-transfer fluid.",
    toxicity_level: "moderate",
    hazard_codes: ["GHS02", "GHS07"],
  },
  {
    atomic_number: 4,
    name: "Beryllium",
    symbol: "Be",
    latin_name: "Beryllium",
    period: 2,
    group: 2,
    block: "s",
    category: "alkaline earth metal",
    phase_at_stp: "solid",
    standard_state_color: "steel-gray",
    atomic_mass: 9.0122,
    density_g_cm3: 1.85,
    valency: [2],
    oxidation_states: [2],
    common_oxidation_state: 2,
    electronic_configuration: {
      full: "1s² 2s²",
      shorthand: "[He] 2s²",
      noble_gas_core: "He",
      valence_electrons: 2,
      electron_shells: [2, 2],
    },
    radii: { atomic: 112, covalent: 96, van_der_waals: 153, ionic: 45 },
    thermodynamics: {
      melting_point_k: 1560,
      boiling_point_k: 2742,
      heat_of_fusion_kj_mol: 12.2,
      heat_of_vaporization_kj_mol: 292,
      specific_heat_j_gk: 1.825,
      thermal_conductivity_w_mk: 200,
    },
    electrical: {
      electronegativity_pauling: 1.57,
      ionization_energies_kj_mol: [899.5, 1757.1, 14848.7],
      electron_affinity_kj_mol: 0,
      electrical_conductivity_s_m: 2.5e7,
      magnetic_type: "diamagnetic",
    },
    abundance: {
      earth_crust_ppm: 2.8,
      ocean_ppm: 0.0006,
      universe_ppm: 1,
      human_body_ppm: null,
    },
    isotopes: [
      { mass_number: 9, natural_abundance_percent: 100, half_life: "stable", decay_mode: null, is_stable: true },
    ],
    radioactive: false,
    stability: "stable",
    discovery: {
      discoverer: "Louis-Nicolas Vauquelin",
      year: 1798,
      location: "France",
      named_after: "Greek: beryllos (beryl gemstone)",
      etymology: "Found in the mineral beryl",
    },
    cas_number: "7440-41-7",
    description: "A lightweight, strong, brittle alkaline earth metal used in aerospace, nuclear reactors, and X-ray equipment. Highly toxic.",
    detailed_description: "Beryllium is a lightweight but very stiff metal with excellent thermal conductivity and low thermal neutron absorption. It is used in aerospace structural components, X-ray windows, and nuclear reactor reflectors. Despite its useful properties, beryllium and its compounds are highly toxic and can cause chronic beryllium disease (berylliosis) upon inhalation.",
    toxicity_level: "extreme",
    hazard_codes: ["GHS06", "GHS08"],
  },
  {
    atomic_number: 5,
    name: "Boron",
    symbol: "B",
    latin_name: "Borum",
    period: 2,
    group: 13,
    block: "p",
    category: "metalloid",
    phase_at_stp: "solid",
    standard_state_color: "black",
    atomic_mass: 10.81,
    density_g_cm3: 2.34,
    valency: [3],
    oxidation_states: [3],
    common_oxidation_state: 3,
    electronic_configuration: {
      full: "1s² 2s² 2p¹",
      shorthand: "[He] 2s² 2p¹",
      noble_gas_core: "He",
      valence_electrons: 3,
      electron_shells: [2, 3],
    },
    radii: { atomic: 87, covalent: 84, van_der_waals: 192, ionic: 27 },
    thermodynamics: {
      melting_point_k: 2349,
      boiling_point_k: 4200,
      heat_of_fusion_kj_mol: 50,
      heat_of_vaporization_kj_mol: 480,
      specific_heat_j_gk: 1.026,
      thermal_conductivity_w_mk: 27.4,
    },
    electrical: {
      electronegativity_pauling: 2.04,
      ionization_energies_kj_mol: [800.6, 2427.1, 3659.7],
      electron_affinity_kj_mol: 26.7,
      electrical_conductivity_s_m: 1e-4,
      magnetic_type: "diamagnetic",
    },
    abundance: {
      earth_crust_ppm: 10,
      ocean_ppm: 4.5,
      universe_ppm: 10,
      human_body_ppm: null,
    },
    isotopes: [
      { mass_number: 10, natural_abundance_percent: 19.9, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 11, natural_abundance_percent: 80.1, half_life: "stable", decay_mode: null, is_stable: true },
    ],
    radioactive: false,
    stability: "stable",
    discovery: {
      discoverer: "Humphry Davy / Joseph Louis Gay-Lussac / Louis Jacques Thénard",
      year: 1808,
      location: "England / France",
      named_after: "Arabic: buraq (borax)",
      etymology: "From the mineral borax",
    },
    cas_number: "7440-42-8",
    description: "A metalloid essential in borosilicate glass, borax detergents, nuclear control rods, and plant nutrition.",
    detailed_description: "Boron is a metalloid that does not occur as a free element in nature. It exists in several allotropic forms, with crystalline boron being one of the hardest materials known. Boron is essential for plant cell walls and is used industrially in borosilicate glass (Pyrex), detergents, and insecticides. Its high neutron absorption cross-section makes it valuable for nuclear reactor control rods.",
    toxicity_level: "low",
    hazard_codes: ["GHS07"],
  },
  {
    atomic_number: 6,
    name: "Carbon",
    symbol: "C",
    latin_name: "Carboneum",
    period: 2,
    group: 14,
    block: "p",
    category: "reactive nonmetal",
    phase_at_stp: "solid",
    standard_state_color: "black (graphite) / transparent (diamond)",
    atomic_mass: 12.011,
    density_g_cm3: 2.267,
    valency: [4],
    oxidation_states: [-4, -3, -2, -1, 0, 1, 2, 3, 4],
    common_oxidation_state: 4,
    electronic_configuration: {
      full: "1s² 2s² 2p²",
      shorthand: "[He] 2s² 2p²",
      noble_gas_core: "He",
      valence_electrons: 4,
      electron_shells: [2, 4],
    },
    radii: { atomic: 77, covalent: 77, van_der_waals: 170, ionic: 16 },
    thermodynamics: {
      melting_point_k: 3915,
      boiling_point_k: 4098,
      heat_of_fusion_kj_mol: 117,
      heat_of_vaporization_kj_mol: 715,
      specific_heat_j_gk: 0.709,
      thermal_conductivity_w_mk: 129,
    },
    electrical: {
      electronegativity_pauling: 2.55,
      ionization_energies_kj_mol: [1086.5, 2352.6, 4620.5],
      electron_affinity_kj_mol: 121.8,
      electrical_conductivity_s_m: 1e5,
      magnetic_type: "diamagnetic",
    },
    abundance: {
      earth_crust_ppm: 200,
      ocean_ppm: 28,
      universe_ppm: 5000,
      human_body_ppm: 230000,
    },
    isotopes: [
      { mass_number: 12, natural_abundance_percent: 98.9, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 13, natural_abundance_percent: 1.1, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 14, natural_abundance_percent: 0, half_life: "5730 yr", decay_mode: "β−", is_stable: false },
    ],
    radioactive: false,
    stability: "stable",
    discovery: {
      discoverer: "Known since antiquity",
      year: null,
      location: null,
      named_after: "Latin: carbo (coal/charcoal)",
      etymology: "From ancient charcoal and coal",
    },
    cas_number: "7440-44-0",
    description: "The basis of all known life and organic chemistry, existing in allotropes including diamond, graphite, graphene, and fullerenes.",
    detailed_description: "Carbon is unique among elements in the vast number and variety of compounds it can form, due to its ability to form up to four stable covalent bonds and to catenate (bond with itself). It is the basis of all known life. Its allotropes range from the hardest natural substance (diamond) to one of the softest (graphite). Carbon-14 is used in radiocarbon dating.",
    toxicity_level: "none",
    hazard_codes: [],
  },
  {
    atomic_number: 7,
    name: "Nitrogen",
    symbol: "N",
    latin_name: "Nitrogenium",
    period: 2,
    group: 15,
    block: "p",
    category: "reactive nonmetal",
    phase_at_stp: "gas",
    standard_state_color: "colorless",
    atomic_mass: 14.007,
    density_g_cm3: 0.0012506,
    valency: [3],
    oxidation_states: [-3, -2, -1, 0, 1, 2, 3, 4, 5],
    common_oxidation_state: -3,
    electronic_configuration: {
      full: "1s² 2s² 2p³",
      shorthand: "[He] 2s² 2p³",
      noble_gas_core: "He",
      valence_electrons: 5,
      electron_shells: [2, 5],
    },
    radii: { atomic: 56, covalent: 71, van_der_waals: 155, ionic: 146 },
    thermodynamics: {
      melting_point_k: 63.15,
      boiling_point_k: 77.36,
      heat_of_fusion_kj_mol: 0.36,
      heat_of_vaporization_kj_mol: 2.79,
      specific_heat_j_gk: 1.04,
      thermal_conductivity_w_mk: 0.02583,
    },
    electrical: {
      electronegativity_pauling: 3.04,
      ionization_energies_kj_mol: [1402.3, 2856, 4578.1],
      electron_affinity_kj_mol: 7,
      electrical_conductivity_s_m: null,
      magnetic_type: "diamagnetic",
    },
    abundance: {
      earth_crust_ppm: 19,
      ocean_ppm: 0.5,
      universe_ppm: 1000,
      human_body_ppm: 26000,
    },
    isotopes: [
      { mass_number: 14, natural_abundance_percent: 99.634, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 15, natural_abundance_percent: 0.366, half_life: "stable", decay_mode: null, is_stable: true },
    ],
    radioactive: false,
    stability: "stable",
    discovery: {
      discoverer: "Daniel Rutherford",
      year: 1772,
      location: "Scotland",
      named_after: "Greek: nitron (niter) + genes (forming)",
      etymology: "Niter-forming",
    },
    cas_number: "7727-37-9",
    description: "Makes up 78% of Earth's atmosphere and is essential to all life as a component of proteins and nucleic acids.",
    detailed_description: "Nitrogen is a colorless, odorless gas that makes up about 78% of Earth's atmosphere. Despite its abundance, atmospheric nitrogen (N₂) is relatively unreactive due to its strong triple bond. It is an essential component of amino acids, proteins, and nucleic acids. The Haber-Bosch process fixes atmospheric nitrogen into ammonia, underpinning modern agriculture.",
    toxicity_level: "none",
    hazard_codes: ["GHS04"],
  },
  {
    atomic_number: 8,
    name: "Oxygen",
    symbol: "O",
    latin_name: "Oxygenium",
    period: 2,
    group: 16,
    block: "p",
    category: "reactive nonmetal",
    phase_at_stp: "gas",
    standard_state_color: "colorless",
    atomic_mass: 15.999,
    density_g_cm3: 0.001429,
    valency: [2],
    oxidation_states: [-2, -1, 0, 1, 2],
    common_oxidation_state: -2,
    electronic_configuration: {
      full: "1s² 2s² 2p⁴",
      shorthand: "[He] 2s² 2p⁴",
      noble_gas_core: "He",
      valence_electrons: 6,
      electron_shells: [2, 6],
    },
    radii: { atomic: 48, covalent: 66, van_der_waals: 152, ionic: 140 },
    thermodynamics: {
      melting_point_k: 54.36,
      boiling_point_k: 90.2,
      heat_of_fusion_kj_mol: 0.444,
      heat_of_vaporization_kj_mol: 3.41,
      specific_heat_j_gk: 0.918,
      thermal_conductivity_w_mk: 0.02658,
    },
    electrical: {
      electronegativity_pauling: 3.44,
      ionization_energies_kj_mol: [1313.9, 3388.3, 5300.5],
      electron_affinity_kj_mol: 141.0,
      electrical_conductivity_s_m: null,
      magnetic_type: "paramagnetic",
    },
    abundance: {
      earth_crust_ppm: 461000,
      ocean_ppm: 857000,
      universe_ppm: 10000,
      human_body_ppm: 650000,
    },
    isotopes: [
      { mass_number: 16, natural_abundance_percent: 99.757, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 17, natural_abundance_percent: 0.038, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 18, natural_abundance_percent: 0.205, half_life: "stable", decay_mode: null, is_stable: true },
    ],
    radioactive: false,
    stability: "stable",
    discovery: {
      discoverer: "Carl Wilhelm Scheele / Joseph Priestley",
      year: 1772,
      location: "Sweden / England",
      named_after: "Greek: oxys (sharp/acid) + genes (forming)",
      etymology: "Acid-forming",
    },
    cas_number: "7782-44-7",
    description: "The third most abundant element in the universe, essential for respiration in most life forms and the most electronegative of the reactive nonmetals.",
    detailed_description: "Oxygen is essential for nearly all known forms of life. It is the most electronegative element after fluorine and readily forms compounds with nearly all other elements. Liquid oxygen is pale blue and highly paramagnetic. The ozone layer (O₃) in the stratosphere protects life from ultraviolet radiation. Oxygen was pivotal in the history of chemistry with the oxygen theory of combustion.",
    toxicity_level: "none",
    hazard_codes: ["GHS03"],
  },
  {
    atomic_number: 9,
    name: "Fluorine",
    symbol: "F",
    latin_name: "Fluorum",
    period: 2,
    group: 17,
    block: "p",
    category: "reactive nonmetal",
    phase_at_stp: "gas",
    standard_state_color: "pale yellow",
    atomic_mass: 18.998,
    density_g_cm3: 0.001696,
    valency: [1],
    oxidation_states: [-1],
    common_oxidation_state: -1,
    electronic_configuration: {
      full: "1s² 2s² 2p⁵",
      shorthand: "[He] 2s² 2p⁵",
      noble_gas_core: "He",
      valence_electrons: 7,
      electron_shells: [2, 7],
    },
    radii: { atomic: 42, covalent: 64, van_der_waals: 147, ionic: 133 },
    thermodynamics: {
      melting_point_k: 53.48,
      boiling_point_k: 85.03,
      heat_of_fusion_kj_mol: 0.51,
      heat_of_vaporization_kj_mol: 3.27,
      specific_heat_j_gk: 0.824,
      thermal_conductivity_w_mk: 0.0277,
    },
    electrical: {
      electronegativity_pauling: 3.98,
      ionization_energies_kj_mol: [1681, 3374.2, 6050.4],
      electron_affinity_kj_mol: 328.0,
      electrical_conductivity_s_m: null,
      magnetic_type: "diamagnetic",
    },
    abundance: {
      earth_crust_ppm: 585,
      ocean_ppm: 1.3,
      universe_ppm: 400,
      human_body_ppm: 37,
    },
    isotopes: [
      { mass_number: 19, natural_abundance_percent: 100, half_life: "stable", decay_mode: null, is_stable: true },
    ],
    radioactive: false,
    stability: "stable",
    discovery: {
      discoverer: "Henri Moissan",
      year: 1886,
      location: "France",
      named_after: "Latin: fluere (to flow)",
      etymology: "From fluorspar mineral",
    },
    cas_number: "7782-41-4",
    description: "The most electronegative and reactive of all elements, a pale yellow gas that will attack almost any substance including glass and noble gas compounds.",
    detailed_description: "Fluorine is the most reactive of all elements and the most electronegative. It forms compounds with nearly every other element, including noble gases like xenon and krypton. It exists as a diatomic gas (F₂) at room temperature. Fluorine's unique reactivity makes it central to the production of uranium hexafluoride for nuclear fuel processing and fluoropolymers like Teflon.",
    toxicity_level: "extreme",
    hazard_codes: ["GHS03", "GHS06", "GHS05", "GHS08"],
  },
  {
    atomic_number: 10,
    name: "Neon",
    symbol: "Ne",
    latin_name: "Neon",
    period: 2,
    group: 18,
    block: "p",
    category: "noble gas",
    phase_at_stp: "gas",
    standard_state_color: "colorless",
    atomic_mass: 20.18,
    density_g_cm3: 0.0008999,
    valency: [0],
    oxidation_states: [0],
    common_oxidation_state: 0,
    electronic_configuration: {
      full: "1s² 2s² 2p⁶",
      shorthand: "1s² 2s² 2p⁶",
      noble_gas_core: null,
      valence_electrons: 8,
      electron_shells: [2, 8],
    },
    radii: { atomic: 38, covalent: 58, van_der_waals: 154, ionic: null },
    thermodynamics: {
      melting_point_k: 24.56,
      boiling_point_k: 27.07,
      heat_of_fusion_kj_mol: 0.34,
      heat_of_vaporization_kj_mol: 1.75,
      specific_heat_j_gk: 1.03,
      thermal_conductivity_w_mk: 0.0491,
    },
    electrical: {
      electronegativity_pauling: null,
      ionization_energies_kj_mol: [2080.7, 3952.3, 6122],
      electron_affinity_kj_mol: 0,
      electrical_conductivity_s_m: null,
      magnetic_type: "diamagnetic",
    },
    abundance: {
      earth_crust_ppm: 0.0005,
      ocean_ppm: 0.00012,
      universe_ppm: 1300,
      human_body_ppm: null,
    },
    isotopes: [
      { mass_number: 20, natural_abundance_percent: 90.48, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 21, natural_abundance_percent: 0.27, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 22, natural_abundance_percent: 9.25, half_life: "stable", decay_mode: null, is_stable: true },
    ],
    radioactive: false,
    stability: "stable",
    discovery: {
      discoverer: "William Ramsay / Morris Travers",
      year: 1898,
      location: "England",
      named_after: "Greek: neos (new)",
      etymology: "The new element",
    },
    cas_number: "7440-01-9",
    description: "An inert noble gas famous for its vivid orange-red glow in neon signs, the fifth most abundant element in the universe.",
    detailed_description: "Neon is a colorless, odorless, inert monatomic gas. It glows a distinctive orange-red when used in discharge tubes, giving the name to 'neon signs' (though many colored signs use other gases). Neon is obtained industrially by fractional distillation of liquid air. It has no known stable chemical compounds and its only significant uses are based on its physical properties.",
    toxicity_level: "none",
    hazard_codes: ["GHS04"],
  },
  // ─── Period 3 (selected core elements, full set continues below) ──────────
  {
    atomic_number: 11,
    name: "Sodium",
    symbol: "Na",
    latin_name: "Natrium",
    period: 3,
    group: 1,
    block: "s",
    category: "alkali metal",
    phase_at_stp: "solid",
    standard_state_color: "silvery-white",
    atomic_mass: 22.99,
    density_g_cm3: 0.968,
    valency: [1],
    oxidation_states: [-1, 1],
    common_oxidation_state: 1,
    electronic_configuration: {
      full: "1s² 2s² 2p⁶ 3s¹",
      shorthand: "[Ne] 3s¹",
      noble_gas_core: "Ne",
      valence_electrons: 1,
      electron_shells: [2, 8, 1],
    },
    radii: { atomic: 186, covalent: 166, van_der_waals: 227, ionic: 102 },
    thermodynamics: {
      melting_point_k: 370.87,
      boiling_point_k: 1156,
      heat_of_fusion_kj_mol: 2.60,
      heat_of_vaporization_kj_mol: 97.7,
      specific_heat_j_gk: 1.228,
      thermal_conductivity_w_mk: 142,
    },
    electrical: {
      electronegativity_pauling: 0.93,
      ionization_energies_kj_mol: [495.8, 4562, 6910.3],
      electron_affinity_kj_mol: 52.8,
      electrical_conductivity_s_m: 2.1e7,
      magnetic_type: "paramagnetic",
    },
    abundance: {
      earth_crust_ppm: 23600,
      ocean_ppm: 10800,
      universe_ppm: 20,
      human_body_ppm: 1400,
    },
    isotopes: [
      { mass_number: 23, natural_abundance_percent: 100, half_life: "stable", decay_mode: null, is_stable: true },
    ],
    radioactive: false,
    stability: "stable",
    discovery: {
      discoverer: "Humphry Davy",
      year: 1807,
      location: "England",
      named_after: "English: soda; symbol from Latin Natrium",
      etymology: "From soda ash (sodium carbonate)",
    },
    cas_number: "7440-23-5",
    description: "A soft, highly reactive alkali metal essential to life, most familiar as the cation in table salt (NaCl).",
    detailed_description: "Sodium is an essential element for all animals and many plants. As the most abundant alkali metal in the human body, it regulates blood pressure and nerve function. It reacts vigorously with water and must be stored under oil. The sodium-potassium pump is fundamental to cellular physiology. Industrially, sodium compounds are among the most produced chemicals worldwide.",
    toxicity_level: "low",
    hazard_codes: ["GHS02"],
  },
  {
    atomic_number: 12,
    name: "Magnesium",
    symbol: "Mg",
    latin_name: "Magnesium",
    period: 3,
    group: 2,
    block: "s",
    category: "alkaline earth metal",
    phase_at_stp: "solid",
    standard_state_color: "silvery-white",
    atomic_mass: 24.305,
    density_g_cm3: 1.738,
    valency: [2],
    oxidation_states: [2],
    common_oxidation_state: 2,
    electronic_configuration: {
      full: "1s² 2s² 2p⁶ 3s²",
      shorthand: "[Ne] 3s²",
      noble_gas_core: "Ne",
      valence_electrons: 2,
      electron_shells: [2, 8, 2],
    },
    radii: { atomic: 160, covalent: 141, van_der_waals: 173, ionic: 72 },
    thermodynamics: {
      melting_point_k: 923,
      boiling_point_k: 1363,
      heat_of_fusion_kj_mol: 8.48,
      heat_of_vaporization_kj_mol: 128,
      specific_heat_j_gk: 1.023,
      thermal_conductivity_w_mk: 156,
    },
    electrical: {
      electronegativity_pauling: 1.31,
      ionization_energies_kj_mol: [737.7, 1450.7, 7732.7],
      electron_affinity_kj_mol: 0,
      electrical_conductivity_s_m: 2.3e7,
      magnetic_type: "paramagnetic",
    },
    abundance: {
      earth_crust_ppm: 23300,
      ocean_ppm: 1290,
      universe_ppm: 580,
      human_body_ppm: 270,
    },
    isotopes: [
      { mass_number: 24, natural_abundance_percent: 78.99, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 25, natural_abundance_percent: 10.00, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 26, natural_abundance_percent: 11.01, half_life: "stable", decay_mode: null, is_stable: true },
    ],
    radioactive: false,
    stability: "stable",
    discovery: {
      discoverer: "Humphry Davy",
      year: 1808,
      location: "England",
      named_after: "Magnesia, a district in Greece",
      etymology: "From the Magnesia district where magnesite was found",
    },
    cas_number: "7439-95-4",
    description: "A lightweight structural metal and essential biological element, central to the chlorophyll molecule in plants.",
    detailed_description: "Magnesium is the eighth most abundant element in Earth's crust and the fourth most common element in Earth as a whole. It is central to the chlorophyll molecule in plants, making it vital for photosynthesis. In humans, it is required for over 300 enzymatic reactions. As a metal, it is the lightest structural metal used in engineering, valued for its strength-to-weight ratio.",
    toxicity_level: "none",
    hazard_codes: ["GHS02"],
  },
  {
    atomic_number: 13,
    name: "Aluminum",
    symbol: "Al",
    latin_name: "Aluminium",
    period: 3,
    group: 13,
    block: "p",
    category: "post-transition metal",
    phase_at_stp: "solid",
    standard_state_color: "silvery-white",
    atomic_mass: 26.982,
    density_g_cm3: 2.7,
    valency: [3],
    oxidation_states: [1, 3],
    common_oxidation_state: 3,
    electronic_configuration: {
      full: "1s² 2s² 2p⁶ 3s² 3p¹",
      shorthand: "[Ne] 3s² 3p¹",
      noble_gas_core: "Ne",
      valence_electrons: 3,
      electron_shells: [2, 8, 3],
    },
    radii: { atomic: 143, covalent: 121, van_der_waals: 184, ionic: 53 },
    thermodynamics: {
      melting_point_k: 933.47,
      boiling_point_k: 2792,
      heat_of_fusion_kj_mol: 10.71,
      heat_of_vaporization_kj_mol: 284,
      specific_heat_j_gk: 0.897,
      thermal_conductivity_w_mk: 237,
    },
    electrical: {
      electronegativity_pauling: 1.61,
      ionization_energies_kj_mol: [577.5, 1816.7, 2744.8],
      electron_affinity_kj_mol: 41.8,
      electrical_conductivity_s_m: 3.77e7,
      magnetic_type: "paramagnetic",
    },
    abundance: {
      earth_crust_ppm: 82300,
      ocean_ppm: 0.002,
      universe_ppm: 58,
      human_body_ppm: null,
    },
    isotopes: [
      { mass_number: 27, natural_abundance_percent: 100, half_life: "stable", decay_mode: null, is_stable: true },
    ],
    radioactive: false,
    stability: "stable",
    discovery: {
      discoverer: "Hans Christian Ørsted",
      year: 1825,
      location: "Denmark",
      named_after: "Latin: alumen (alum)",
      etymology: "From alum, a historically important compound",
    },
    cas_number: "7429-90-5",
    description: "The most abundant metal in Earth's crust, valued for its light weight, corrosion resistance, and excellent electrical conductivity.",
    detailed_description: "Aluminum is the most abundant metal in Earth's crust and the third most abundant element overall. It naturally forms a thin, protective oxide layer that makes it highly resistant to corrosion. Because of its excellent strength-to-weight ratio, electrical conductivity, and recyclability, it is used in aircraft, vehicles, packaging, construction, and electrical transmission lines.",
    toxicity_level: "low",
    hazard_codes: ["GHS02"],
  },
  {
    atomic_number: 14,
    name: "Silicon",
    symbol: "Si",
    latin_name: "Silicium",
    period: 3,
    group: 14,
    block: "p",
    category: "metalloid",
    phase_at_stp: "solid",
    standard_state_color: "blue-gray metallic luster",
    atomic_mass: 28.085,
    density_g_cm3: 2.329,
    valency: [4],
    oxidation_states: [-4, -3, -2, -1, 0, 1, 2, 3, 4],
    common_oxidation_state: 4,
    electronic_configuration: {
      full: "1s² 2s² 2p⁶ 3s² 3p²",
      shorthand: "[Ne] 3s² 3p²",
      noble_gas_core: "Ne",
      valence_electrons: 4,
      electron_shells: [2, 8, 4],
    },
    radii: { atomic: 111, covalent: 111, van_der_waals: 210, ionic: 40 },
    thermodynamics: {
      melting_point_k: 1687,
      boiling_point_k: 3538,
      heat_of_fusion_kj_mol: 50.2,
      heat_of_vaporization_kj_mol: 359,
      specific_heat_j_gk: 0.705,
      thermal_conductivity_w_mk: 148,
    },
    electrical: {
      electronegativity_pauling: 1.9,
      ionization_energies_kj_mol: [786.5, 1577.1, 3231.6],
      electron_affinity_kj_mol: 133.6,
      electrical_conductivity_s_m: 4.4e-4,
      magnetic_type: "diamagnetic",
    },
    abundance: {
      earth_crust_ppm: 282000,
      ocean_ppm: 2.2,
      universe_ppm: 650,
      human_body_ppm: 26,
    },
    isotopes: [
      { mass_number: 28, natural_abundance_percent: 92.23, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 29, natural_abundance_percent: 4.67, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 30, natural_abundance_percent: 3.1, half_life: "stable", decay_mode: null, is_stable: true },
    ],
    radioactive: false,
    stability: "stable",
    discovery: {
      discoverer: "Jöns Jacob Berzelius",
      year: 1824,
      location: "Sweden",
      named_after: "Latin: silex (flint)",
      etymology: "From silica (silicon dioxide, found in flint)",
    },
    cas_number: "7440-21-3",
    description: "The second most abundant element in Earth's crust and the foundation of modern electronics and computing.",
    detailed_description: "Silicon is the backbone of modern electronics. As a semiconductor, it is the primary material for integrated circuits, solar cells, and transistors. It does not occur free in nature but is found as silica (SiO₂) and silicates. Together with carbon, it forms the basis of silicone polymers. Silicon dioxide (quartz glass) is one of the most widely used materials in technology.",
    toxicity_level: "low",
    hazard_codes: [],
  },
  {
    atomic_number: 15,
    name: "Phosphorus",
    symbol: "P",
    latin_name: "Phosphorus",
    period: 3,
    group: 15,
    block: "p",
    category: "reactive nonmetal",
    phase_at_stp: "solid",
    standard_state_color: "white (waxy) / red (powder)",
    atomic_mass: 30.974,
    density_g_cm3: 1.823,
    valency: [3, 5],
    oxidation_states: [-3, -2, -1, 0, 1, 2, 3, 4, 5],
    common_oxidation_state: 5,
    electronic_configuration: {
      full: "1s² 2s² 2p⁶ 3s² 3p³",
      shorthand: "[Ne] 3s² 3p³",
      noble_gas_core: "Ne",
      valence_electrons: 5,
      electron_shells: [2, 8, 5],
    },
    radii: { atomic: 98, covalent: 107, van_der_waals: 180, ionic: 44 },
    thermodynamics: {
      melting_point_k: 317.3,
      boiling_point_k: 550,
      heat_of_fusion_kj_mol: 0.657,
      heat_of_vaporization_kj_mol: 12.4,
      specific_heat_j_gk: 0.769,
      thermal_conductivity_w_mk: 0.236,
    },
    electrical: {
      electronegativity_pauling: 2.19,
      ionization_energies_kj_mol: [1011.8, 1907, 2914.1],
      electron_affinity_kj_mol: 72.0,
      electrical_conductivity_s_m: 1e-7,
      magnetic_type: "diamagnetic",
    },
    abundance: {
      earth_crust_ppm: 1050,
      ocean_ppm: 0.06,
      universe_ppm: 7,
      human_body_ppm: 11000,
    },
    isotopes: [
      { mass_number: 31, natural_abundance_percent: 100, half_life: "stable", decay_mode: null, is_stable: true },
    ],
    radioactive: false,
    stability: "stable",
    discovery: {
      discoverer: "Hennig Brand",
      year: 1669,
      location: "Germany",
      named_after: "Greek: phosphoros (light-bearing)",
      etymology: "Refers to its white allotrope's glow in air",
    },
    cas_number: "7723-14-0",
    description: "An essential element for all life, found in DNA, RNA, ATP, and bones; white phosphorus is extremely toxic and pyrophoric.",
    detailed_description: "Phosphorus exists in several allotropic forms, notably white and red phosphorus. White phosphorus is highly toxic and ignites spontaneously in air. Red phosphorus is stable and used in matches. Phosphorus is essential for life: it forms the backbone of DNA and RNA, is a component of ATP (cellular energy), and is critical for bone mineralization. Phosphate fertilizers rely on it.",
    toxicity_level: "high",
    hazard_codes: ["GHS02", "GHS06"],
  },
  {
    atomic_number: 16,
    name: "Sulfur",
    symbol: "S",
    latin_name: "Sulphur",
    period: 3,
    group: 16,
    block: "p",
    category: "reactive nonmetal",
    phase_at_stp: "solid",
    standard_state_color: "bright yellow",
    atomic_mass: 32.06,
    density_g_cm3: 2.067,
    valency: [2, 4, 6],
    oxidation_states: [-2, -1, 0, 1, 2, 3, 4, 5, 6],
    common_oxidation_state: -2,
    electronic_configuration: {
      full: "1s² 2s² 2p⁶ 3s² 3p⁴",
      shorthand: "[Ne] 3s² 3p⁴",
      noble_gas_core: "Ne",
      valence_electrons: 6,
      electron_shells: [2, 8, 6],
    },
    radii: { atomic: 88, covalent: 105, van_der_waals: 180, ionic: 184 },
    thermodynamics: {
      melting_point_k: 388.36,
      boiling_point_k: 717.87,
      heat_of_fusion_kj_mol: 1.727,
      heat_of_vaporization_kj_mol: 9.8,
      specific_heat_j_gk: 0.708,
      thermal_conductivity_w_mk: 0.205,
    },
    electrical: {
      electronegativity_pauling: 2.58,
      ionization_energies_kj_mol: [999.6, 2252, 3357],
      electron_affinity_kj_mol: 200.4,
      electrical_conductivity_s_m: 1e-15,
      magnetic_type: "diamagnetic",
    },
    abundance: {
      earth_crust_ppm: 350,
      ocean_ppm: 905,
      universe_ppm: 440,
      human_body_ppm: 2000,
    },
    isotopes: [
      { mass_number: 32, natural_abundance_percent: 94.99, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 33, natural_abundance_percent: 0.75, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 34, natural_abundance_percent: 4.25, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 36, natural_abundance_percent: 0.01, half_life: "stable", decay_mode: null, is_stable: true },
    ],
    radioactive: false,
    stability: "stable",
    discovery: {
      discoverer: "Known since antiquity",
      year: null,
      location: null,
      named_after: "Sanskrit: sulvere / Latin: sulphurium",
      etymology: "Ancient name, origin unclear",
    },
    cas_number: "7704-34-9",
    description: "A bright-yellow solid essential for proteins, amino acids, and the production of sulfuric acid — the world's most widely produced chemical.",
    detailed_description: "Sulfur is found naturally as a pure element near volcanic regions. It has several allotropes, with rhombic sulfur being the most stable. It is an essential element for all living organisms as a component of amino acids. Sulfur is the starting material for sulfuric acid (H₂SO₄), the world's most produced industrial chemical, used in fertilizers, acid-lead batteries, and chemical synthesis.",
    toxicity_level: "low",
    hazard_codes: ["GHS02"],
  },
  {
    atomic_number: 17,
    name: "Chlorine",
    symbol: "Cl",
    latin_name: "Chlorum",
    period: 3,
    group: 17,
    block: "p",
    category: "reactive nonmetal",
    phase_at_stp: "gas",
    standard_state_color: "yellow-green",
    atomic_mass: 35.45,
    density_g_cm3: 0.003214,
    valency: [1, 3, 5, 7],
    oxidation_states: [-1, 0, 1, 2, 3, 4, 5, 6, 7],
    common_oxidation_state: -1,
    electronic_configuration: {
      full: "1s² 2s² 2p⁶ 3s² 3p⁵",
      shorthand: "[Ne] 3s² 3p⁵",
      noble_gas_core: "Ne",
      valence_electrons: 7,
      electron_shells: [2, 8, 7],
    },
    radii: { atomic: 79, covalent: 102, van_der_waals: 175, ionic: 181 },
    thermodynamics: {
      melting_point_k: 171.6,
      boiling_point_k: 239.11,
      heat_of_fusion_kj_mol: 3.2,
      heat_of_vaporization_kj_mol: 10.2,
      specific_heat_j_gk: 0.479,
      thermal_conductivity_w_mk: 0.0089,
    },
    electrical: {
      electronegativity_pauling: 3.16,
      ionization_energies_kj_mol: [1251.2, 2298, 3822],
      electron_affinity_kj_mol: 348.6,
      electrical_conductivity_s_m: null,
      magnetic_type: "diamagnetic",
    },
    abundance: {
      earth_crust_ppm: 145,
      ocean_ppm: 19400,
      universe_ppm: 210,
      human_body_ppm: 1200,
    },
    isotopes: [
      { mass_number: 35, natural_abundance_percent: 75.77, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 37, natural_abundance_percent: 24.23, half_life: "stable", decay_mode: null, is_stable: true },
    ],
    radioactive: false,
    stability: "stable",
    discovery: {
      discoverer: "Carl Wilhelm Scheele",
      year: 1774,
      location: "Sweden",
      named_after: "Greek: chloros (pale green)",
      etymology: "From its yellowish-green color",
    },
    cas_number: "7782-50-5",
    description: "A toxic, yellow-green halogen gas used in water purification, PVC production, and bleaching agents.",
    detailed_description: "Chlorine is a reactive halogen with a pungent, distinctive smell. It was used as a chemical weapon in World War I. Today, it is essential for water purification (killing pathogens), manufacturing PVC plastic, producing solvents, and as a bleaching agent in the paper and textile industry. Sodium chloride (common salt) is its most familiar compound.",
    toxicity_level: "high",
    hazard_codes: ["GHS03", "GHS06", "GHS05", "GHS08", "GHS09"],
  },
  {
    atomic_number: 18,
    name: "Argon",
    symbol: "Ar",
    latin_name: "Argon",
    period: 3,
    group: 18,
    block: "p",
    category: "noble gas",
    phase_at_stp: "gas",
    standard_state_color: "colorless",
    atomic_mass: 39.948,
    density_g_cm3: 0.0017837,
    valency: [0],
    oxidation_states: [0],
    common_oxidation_state: 0,
    electronic_configuration: {
      full: "1s² 2s² 2p⁶ 3s² 3p⁶",
      shorthand: "1s² 2s² 2p⁶ 3s² 3p⁶",
      noble_gas_core: null,
      valence_electrons: 8,
      electron_shells: [2, 8, 8],
    },
    radii: { atomic: 71, covalent: 106, van_der_waals: 188, ionic: null },
    thermodynamics: {
      melting_point_k: 83.8,
      boiling_point_k: 87.3,
      heat_of_fusion_kj_mol: 1.18,
      heat_of_vaporization_kj_mol: 6.53,
      specific_heat_j_gk: 0.52,
      thermal_conductivity_w_mk: 0.01772,
    },
    electrical: {
      electronegativity_pauling: null,
      ionization_energies_kj_mol: [1520.6, 2665.8, 3931],
      electron_affinity_kj_mol: 0,
      electrical_conductivity_s_m: null,
      magnetic_type: "diamagnetic",
    },
    abundance: {
      earth_crust_ppm: 3.5,
      ocean_ppm: 0.45,
      universe_ppm: 1500,
      human_body_ppm: null,
    },
    isotopes: [
      { mass_number: 36, natural_abundance_percent: 0.34, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 38, natural_abundance_percent: 0.06, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 40, natural_abundance_percent: 99.6, half_life: "stable", decay_mode: null, is_stable: true },
    ],
    radioactive: false,
    stability: "stable",
    discovery: {
      discoverer: "Lord Rayleigh / William Ramsay",
      year: 1894,
      location: "England",
      named_after: "Greek: argos (idle/lazy)",
      etymology: "Refers to its chemical inertness",
    },
    cas_number: "7440-37-1",
    description: "The most abundant noble gas in Earth's atmosphere (nearly 1%), used as an inert shielding gas in welding and metal production.",
    detailed_description: "Argon is the third most abundant gas in Earth's atmosphere at about 0.93% by volume. It is used extensively as an inert shielding gas in arc welding and metal cutting to protect the metal from oxidation, in incandescent and fluorescent light bulbs to prevent filament oxidation, and in geochronology (potassium-argon dating). Its isotope ratios are used to study planetary atmospheres.",
    toxicity_level: "none",
    hazard_codes: ["GHS04"],
  },
  // ─── Period 4 key elements ─────────────────────────────────
  {
    atomic_number: 19,
    name: "Potassium",
    symbol: "K",
    latin_name: "Kalium",
    period: 4,
    group: 1,
    block: "s",
    category: "alkali metal",
    phase_at_stp: "solid",
    standard_state_color: "silvery-white",
    atomic_mass: 39.098,
    density_g_cm3: 0.862,
    valency: [1],
    oxidation_states: [-1, 1],
    common_oxidation_state: 1,
    electronic_configuration: {
      full: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s¹",
      shorthand: "[Ar] 4s¹",
      noble_gas_core: "Ar",
      valence_electrons: 1,
      electron_shells: [2, 8, 8, 1],
    },
    radii: { atomic: 243, covalent: 203, van_der_waals: 275, ionic: 138 },
    thermodynamics: {
      melting_point_k: 336.53,
      boiling_point_k: 1032,
      heat_of_fusion_kj_mol: 2.33,
      heat_of_vaporization_kj_mol: 76.9,
      specific_heat_j_gk: 0.757,
      thermal_conductivity_w_mk: 102.5,
    },
    electrical: {
      electronegativity_pauling: 0.82,
      ionization_energies_kj_mol: [418.8, 3052, 4420],
      electron_affinity_kj_mol: 48.4,
      electrical_conductivity_s_m: 1.4e7,
      magnetic_type: "diamagnetic",
    },
    abundance: {
      earth_crust_ppm: 20900,
      ocean_ppm: 392,
      universe_ppm: 20,
      human_body_ppm: 2000,
    },
    isotopes: [
      { mass_number: 39, natural_abundance_percent: 93.26, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 40, natural_abundance_percent: 0.012, half_life: "1.248×10⁹ yr", decay_mode: "β−/β+/EC", is_stable: false },
      { mass_number: 41, natural_abundance_percent: 6.73, half_life: "stable", decay_mode: null, is_stable: true },
    ],
    radioactive: false,
    stability: "stable",
    discovery: {
      discoverer: "Humphry Davy",
      year: 1807,
      location: "England",
      named_after: "English: potash; symbol from Latin Kalium",
      etymology: "From potash (potassium carbonate)",
    },
    cas_number: "7440-09-7",
    description: "An essential electrolyte that maintains cellular membrane potential and heart rhythm; the seventh most abundant element in Earth's crust.",
    detailed_description: "Potassium is vital to human health, maintaining cellular fluid balance and enabling nerve impulse transmission and muscle contraction. The sodium-potassium ATPase pump is fundamental to cellular physiology. Potassium is also crucial for plant growth and is a key component of fertilizers. It reacts even more vigorously with water than sodium, igniting on contact.",
    toxicity_level: "low",
    hazard_codes: ["GHS02"],
  },
  {
    atomic_number: 20,
    name: "Calcium",
    symbol: "Ca",
    latin_name: "Calcium",
    period: 4,
    group: 2,
    block: "s",
    category: "alkaline earth metal",
    phase_at_stp: "solid",
    standard_state_color: "silvery-white",
    atomic_mass: 40.078,
    density_g_cm3: 1.55,
    valency: [2],
    oxidation_states: [2],
    common_oxidation_state: 2,
    electronic_configuration: {
      full: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s²",
      shorthand: "[Ar] 4s²",
      noble_gas_core: "Ar",
      valence_electrons: 2,
      electron_shells: [2, 8, 8, 2],
    },
    radii: { atomic: 197, covalent: 176, van_der_waals: 231, ionic: 100 },
    thermodynamics: {
      melting_point_k: 1115,
      boiling_point_k: 1757,
      heat_of_fusion_kj_mol: 8.54,
      heat_of_vaporization_kj_mol: 154.7,
      specific_heat_j_gk: 0.647,
      thermal_conductivity_w_mk: 201,
    },
    electrical: {
      electronegativity_pauling: 1.0,
      ionization_energies_kj_mol: [589.8, 1145.4, 4912.4],
      electron_affinity_kj_mol: 2.37,
      electrical_conductivity_s_m: 2.98e7,
      magnetic_type: "diamagnetic",
    },
    abundance: {
      earth_crust_ppm: 41500,
      ocean_ppm: 412,
      universe_ppm: 70,
      human_body_ppm: 15000,
    },
    isotopes: [
      { mass_number: 40, natural_abundance_percent: 96.94, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 42, natural_abundance_percent: 0.647, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 43, natural_abundance_percent: 0.135, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 44, natural_abundance_percent: 2.09, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 46, natural_abundance_percent: 0.004, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 48, natural_abundance_percent: 0.187, half_life: ">4×10¹⁹ yr", decay_mode: "β−β−", is_stable: false },
    ],
    radioactive: false,
    stability: "stable",
    discovery: {
      discoverer: "Humphry Davy",
      year: 1808,
      location: "England",
      named_after: "Latin: calx (lime)",
      etymology: "From calcium oxide (lime), historically important building material",
    },
    cas_number: "7440-70-2",
    description: "The most abundant metal in the human body, essential for bones, teeth, muscle function, and nerve signaling.",
    detailed_description: "Calcium is the fifth most abundant element in Earth's crust and the most abundant metal in the human body. It is essential for bone and tooth formation (as hydroxyapatite), muscle contraction, nerve transmission, and blood clotting. Calcium compounds include limestone, marble, and chalk (CaCO₃), which are among the most widely used minerals in construction and industry.",
    toxicity_level: "none",
    hazard_codes: ["GHS02"],
  },
  {
    atomic_number: 26,
    name: "Iron",
    symbol: "Fe",
    latin_name: "Ferrum",
    period: 4,
    group: 8,
    block: "d",
    category: "transition metal",
    phase_at_stp: "solid",
    standard_state_color: "metallic gray",
    atomic_mass: 55.845,
    density_g_cm3: 7.874,
    valency: [2, 3],
    oxidation_states: [-2, -1, 0, 1, 2, 3, 4, 5, 6],
    common_oxidation_state: 3,
    electronic_configuration: {
      full: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d⁶ 4s²",
      shorthand: "[Ar] 3d⁶ 4s²",
      noble_gas_core: "Ar",
      valence_electrons: 8,
      electron_shells: [2, 8, 14, 2],
    },
    radii: { atomic: 126, covalent: 132, van_der_waals: null, ionic: 65 },
    thermodynamics: {
      melting_point_k: 1811,
      boiling_point_k: 3134,
      heat_of_fusion_kj_mol: 13.81,
      heat_of_vaporization_kj_mol: 340,
      specific_heat_j_gk: 0.449,
      thermal_conductivity_w_mk: 80.4,
    },
    electrical: {
      electronegativity_pauling: 1.83,
      ionization_energies_kj_mol: [762.5, 1561.9, 2957],
      electron_affinity_kj_mol: 15.7,
      electrical_conductivity_s_m: 1.04e7,
      magnetic_type: "ferromagnetic",
    },
    abundance: {
      earth_crust_ppm: 56300,
      ocean_ppm: 0.002,
      universe_ppm: 1100,
      human_body_ppm: 60,
    },
    isotopes: [
      { mass_number: 54, natural_abundance_percent: 5.85, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 56, natural_abundance_percent: 91.75, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 57, natural_abundance_percent: 2.12, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 58, natural_abundance_percent: 0.28, half_life: "stable", decay_mode: null, is_stable: true },
    ],
    radioactive: false,
    stability: "stable",
    discovery: {
      discoverer: "Known since antiquity",
      year: null,
      location: null,
      named_after: "Anglo-Saxon: iron; symbol from Latin Ferrum",
      etymology: "Ancient name from its widespread use",
    },
    cas_number: "7439-89-6",
    description: "The most used metal in the world by mass; forms steel when alloyed with carbon; essential for oxygen transport in hemoglobin.",
    detailed_description: "Iron is the fourth most abundant element in Earth's crust and is the primary component of Earth's core. It is the most used of all metals, primarily in the form of steel (iron-carbon alloy). Iron is biologically essential as the active center of hemoglobin, enabling red blood cells to transport oxygen. Iron deficiency anemia is the world's most common nutritional deficiency.",
    toxicity_level: "low",
    hazard_codes: [],
  },
  {
    atomic_number: 29,
    name: "Copper",
    symbol: "Cu",
    latin_name: "Cuprum",
    period: 4,
    group: 11,
    block: "d",
    category: "transition metal",
    phase_at_stp: "solid",
    standard_state_color: "red-orange metallic",
    atomic_mass: 63.546,
    density_g_cm3: 8.96,
    valency: [1, 2],
    oxidation_states: [0, 1, 2, 3, 4],
    common_oxidation_state: 2,
    electronic_configuration: {
      full: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s¹",
      shorthand: "[Ar] 3d¹⁰ 4s¹",
      noble_gas_core: "Ar",
      valence_electrons: 1,
      electron_shells: [2, 8, 18, 1],
    },
    radii: { atomic: 128, covalent: 132, van_der_waals: 140, ionic: 73 },
    thermodynamics: {
      melting_point_k: 1357.77,
      boiling_point_k: 2835,
      heat_of_fusion_kj_mol: 13.05,
      heat_of_vaporization_kj_mol: 300.4,
      specific_heat_j_gk: 0.385,
      thermal_conductivity_w_mk: 401,
    },
    electrical: {
      electronegativity_pauling: 1.9,
      ionization_energies_kj_mol: [745.5, 1957.9, 3555],
      electron_affinity_kj_mol: 118.4,
      electrical_conductivity_s_m: 5.96e7,
      magnetic_type: "diamagnetic",
    },
    abundance: {
      earth_crust_ppm: 68,
      ocean_ppm: 0.0003,
      universe_ppm: 0.6,
      human_body_ppm: 1,
    },
    isotopes: [
      { mass_number: 63, natural_abundance_percent: 69.15, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 65, natural_abundance_percent: 30.85, half_life: "stable", decay_mode: null, is_stable: true },
    ],
    radioactive: false,
    stability: "stable",
    discovery: {
      discoverer: "Known since antiquity",
      year: null,
      location: null,
      named_after: "Latin: Cuprum (from Cyprus island)",
      etymology: "Named after Cyprus, ancient major source",
    },
    cas_number: "7440-50-8",
    description: "One of the oldest metals used by humans, with outstanding electrical conductivity; essential for electrical wiring, plumbing, and as a biological trace element.",
    detailed_description: "Copper was one of the first metals worked by humans, giving rise to the Copper Age. It has the highest electrical conductivity of any metal after silver, making it indispensable for electrical wiring. Copper is naturally antimicrobial and is used in hospital surfaces. It is an essential trace element in human biology, required for enzyme function and iron metabolism. Brass and bronze are its most important alloys.",
    toxicity_level: "low",
    hazard_codes: ["GHS09"],
  },
  {
    atomic_number: 30,
    name: "Zinc",
    symbol: "Zn",
    latin_name: "Zincum",
    period: 4,
    group: 12,
    block: "d",
    category: "transition metal",
    phase_at_stp: "solid",
    standard_state_color: "bluish-white",
    atomic_mass: 65.38,
    density_g_cm3: 7.133,
    valency: [2],
    oxidation_states: [0, 1, 2],
    common_oxidation_state: 2,
    electronic_configuration: {
      full: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s²",
      shorthand: "[Ar] 3d¹⁰ 4s²",
      noble_gas_core: "Ar",
      valence_electrons: 2,
      electron_shells: [2, 8, 18, 2],
    },
    radii: { atomic: 134, covalent: 122, van_der_waals: 139, ionic: 74 },
    thermodynamics: {
      melting_point_k: 692.68,
      boiling_point_k: 1180,
      heat_of_fusion_kj_mol: 7.35,
      heat_of_vaporization_kj_mol: 123.6,
      specific_heat_j_gk: 0.388,
      thermal_conductivity_w_mk: 116,
    },
    electrical: {
      electronegativity_pauling: 1.65,
      ionization_energies_kj_mol: [906.4, 1733.3, 3833],
      electron_affinity_kj_mol: 0,
      electrical_conductivity_s_m: 1.69e7,
      magnetic_type: "diamagnetic",
    },
    abundance: {
      earth_crust_ppm: 79,
      ocean_ppm: 0.0005,
      universe_ppm: 0.3,
      human_body_ppm: 33,
    },
    isotopes: [
      { mass_number: 64, natural_abundance_percent: 48.6, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 66, natural_abundance_percent: 27.9, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 67, natural_abundance_percent: 4.1, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 68, natural_abundance_percent: 18.8, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 70, natural_abundance_percent: 0.6, half_life: "stable", decay_mode: null, is_stable: true },
    ],
    radioactive: false,
    stability: "stable",
    discovery: {
      discoverer: "Andreas Sigismund Marggraf",
      year: 1746,
      location: "Germany",
      named_after: "German: Zinke (tooth/prong)",
      etymology: "From the shape of zinc crystals",
    },
    cas_number: "7440-66-6",
    description: "An essential trace mineral for immune function, wound healing, and protein synthesis; used to galvanize steel against corrosion.",
    detailed_description: "Zinc is the fourth most common metal in industrial use and is crucial for human health. It is required for the activity of over 300 enzymes and is important for immune function, protein synthesis, wound healing, DNA synthesis, and cell division. Industrially, its primary use is galvanizing steel to prevent rusting. Zinc-carbon and alkaline batteries are important applications.",
    toxicity_level: "low",
    hazard_codes: ["GHS02", "GHS09"],
  },
  // ─── Noble gases / key period 4-7 elements ───────────────
  {
    atomic_number: 36,
    name: "Krypton",
    symbol: "Kr",
    latin_name: "Krypton",
    period: 4,
    group: 18,
    block: "p",
    category: "noble gas",
    phase_at_stp: "gas",
    standard_state_color: "colorless",
    atomic_mass: 83.798,
    density_g_cm3: 0.003749,
    valency: [0],
    oxidation_states: [0, 2],
    common_oxidation_state: 0,
    electronic_configuration: {
      full: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶",
      shorthand: "[Ar] 3d¹⁰ 4s² 4p⁶",
      noble_gas_core: "Ar",
      valence_electrons: 8,
      electron_shells: [2, 8, 18, 8],
    },
    radii: { atomic: 88, covalent: 116, van_der_waals: 202, ionic: null },
    thermodynamics: {
      melting_point_k: 115.79,
      boiling_point_k: 119.93,
      heat_of_fusion_kj_mol: 1.64,
      heat_of_vaporization_kj_mol: 9.08,
      specific_heat_j_gk: 0.248,
      thermal_conductivity_w_mk: 0.00943,
    },
    electrical: {
      electronegativity_pauling: 3.0,
      ionization_energies_kj_mol: [1350.8, 2350.4, 3565],
      electron_affinity_kj_mol: 0,
      electrical_conductivity_s_m: null,
      magnetic_type: "diamagnetic",
    },
    abundance: {
      earth_crust_ppm: 0.0001,
      ocean_ppm: 0.00021,
      universe_ppm: 45,
      human_body_ppm: null,
    },
    isotopes: [
      { mass_number: 78, natural_abundance_percent: 0.36, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 80, natural_abundance_percent: 2.29, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 82, natural_abundance_percent: 11.59, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 83, natural_abundance_percent: 11.5, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 84, natural_abundance_percent: 56.99, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 86, natural_abundance_percent: 17.27, half_life: "stable", decay_mode: null, is_stable: true },
    ],
    radioactive: false,
    stability: "stable",
    discovery: {
      discoverer: "William Ramsay / Morris Travers",
      year: 1898,
      location: "England",
      named_after: "Greek: kryptos (hidden)",
      etymology: "The hidden element",
    },
    cas_number: "7439-90-9",
    description: "A colorless noble gas that emits brilliant white light in lasers and is used in high-performance lighting.",
    detailed_description: "Krypton is a colorless, odorless, monatomic noble gas. Unlike lighter noble gases, krypton can form some compounds, most notably krypton difluoride (KrF₂). It is used in certain types of photographic flash lamps and in krypton fluoride lasers. A krypton-86 spectral line was previously used as the international standard for the definition of the meter.",
    toxicity_level: "none",
    hazard_codes: ["GHS04"],
  },
  {
    atomic_number: 47,
    name: "Silver",
    symbol: "Ag",
    latin_name: "Argentum",
    period: 5,
    group: 11,
    block: "d",
    category: "transition metal",
    phase_at_stp: "solid",
    standard_state_color: "lustrous white metallic",
    atomic_mass: 107.868,
    density_g_cm3: 10.49,
    valency: [1],
    oxidation_states: [-2, -1, 0, 1, 2, 3],
    common_oxidation_state: 1,
    electronic_configuration: {
      full: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s¹",
      shorthand: "[Kr] 4d¹⁰ 5s¹",
      noble_gas_core: "Kr",
      valence_electrons: 1,
      electron_shells: [2, 8, 18, 18, 1],
    },
    radii: { atomic: 165, covalent: 145, van_der_waals: 172, ionic: 115 },
    thermodynamics: {
      melting_point_k: 1234.93,
      boiling_point_k: 2435,
      heat_of_fusion_kj_mol: 11.28,
      heat_of_vaporization_kj_mol: 250.58,
      specific_heat_j_gk: 0.235,
      thermal_conductivity_w_mk: 429,
    },
    electrical: {
      electronegativity_pauling: 1.93,
      ionization_energies_kj_mol: [731.0, 2070, 3361],
      electron_affinity_kj_mol: 125.6,
      electrical_conductivity_s_m: 6.3e7,
      magnetic_type: "diamagnetic",
    },
    abundance: {
      earth_crust_ppm: 0.075,
      ocean_ppm: 0.00001,
      universe_ppm: 0.006,
      human_body_ppm: null,
    },
    isotopes: [
      { mass_number: 107, natural_abundance_percent: 51.84, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 109, natural_abundance_percent: 48.16, half_life: "stable", decay_mode: null, is_stable: true },
    ],
    radioactive: false,
    stability: "stable",
    discovery: {
      discoverer: "Known since antiquity",
      year: null,
      location: null,
      named_after: "Anglo-Saxon: seolfor; symbol from Latin Argentum",
      etymology: "Ancient name for the precious metal",
    },
    cas_number: "7440-22-4",
    description: "The element with the highest electrical and thermal conductivity; used in jewelry, photography, electronics, and antimicrobial applications.",
    detailed_description: "Silver has the highest electrical conductivity, thermal conductivity, and reflectivity of all metals. It has been used as currency and jewelry for thousands of years. Silver's antimicrobial properties make it useful in wound dressings, water purification, and medical devices. The photography industry historically consumed large amounts of silver, though digital photography has reduced this. Silver nanoparticles are used in electronics and medicine.",
    toxicity_level: "low",
    hazard_codes: ["GHS09"],
  },
  {
    atomic_number: 53,
    name: "Iodine",
    symbol: "I",
    latin_name: "Iodum",
    period: 5,
    group: 17,
    block: "p",
    category: "reactive nonmetal",
    phase_at_stp: "solid",
    standard_state_color: "blue-black lustrous",
    atomic_mass: 126.904,
    density_g_cm3: 4.933,
    valency: [1, 3, 5, 7],
    oxidation_states: [-1, 0, 1, 3, 5, 7],
    common_oxidation_state: -1,
    electronic_configuration: {
      full: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 5p⁵",
      shorthand: "[Kr] 4d¹⁰ 5s² 5p⁵",
      noble_gas_core: "Kr",
      valence_electrons: 7,
      electron_shells: [2, 8, 18, 18, 7],
    },
    radii: { atomic: 140, covalent: 139, van_der_waals: 198, ionic: 220 },
    thermodynamics: {
      melting_point_k: 386.85,
      boiling_point_k: 457.4,
      heat_of_fusion_kj_mol: 7.76,
      heat_of_vaporization_kj_mol: 41.57,
      specific_heat_j_gk: 0.214,
      thermal_conductivity_w_mk: 0.449,
    },
    electrical: {
      electronegativity_pauling: 2.66,
      ionization_energies_kj_mol: [1008.4, 1845.9, 3180],
      electron_affinity_kj_mol: 295.2,
      electrical_conductivity_s_m: 1e-7,
      magnetic_type: "diamagnetic",
    },
    abundance: {
      earth_crust_ppm: 0.45,
      ocean_ppm: 0.064,
      universe_ppm: 0.09,
      human_body_ppm: 0.2,
    },
    isotopes: [
      { mass_number: 127, natural_abundance_percent: 100, half_life: "stable", decay_mode: null, is_stable: true },
    ],
    radioactive: false,
    stability: "stable",
    discovery: {
      discoverer: "Bernard Courtois",
      year: 1811,
      location: "France",
      named_after: "Greek: ioeides (violet)",
      etymology: "From the violet color of its vapor",
    },
    cas_number: "7553-56-2",
    description: "An essential trace element required for thyroid hormone synthesis, and a widely used antiseptic and contrast agent in medical imaging.",
    detailed_description: "Iodine is unique among halogens in being a solid at room temperature. It sublimates readily, forming a beautiful violet vapor. Iodine is essential for production of thyroid hormones that regulate metabolism; iodine deficiency causes goiter. Potassium iodide is added to table salt as a public health measure in many countries. Radioactive iodine-131 is used in thyroid cancer treatment.",
    toxicity_level: "moderate",
    hazard_codes: ["GHS07", "GHS08"],
  },
  {
    atomic_number: 54,
    name: "Xenon",
    symbol: "Xe",
    latin_name: "Xenon",
    period: 5,
    group: 18,
    block: "p",
    category: "noble gas",
    phase_at_stp: "gas",
    standard_state_color: "colorless",
    atomic_mass: 131.293,
    density_g_cm3: 0.005887,
    valency: [0],
    oxidation_states: [0, 1, 2, 4, 6, 8],
    common_oxidation_state: 0,
    electronic_configuration: {
      full: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 5p⁶",
      shorthand: "[Kr] 4d¹⁰ 5s² 5p⁶",
      noble_gas_core: "Kr",
      valence_electrons: 8,
      electron_shells: [2, 8, 18, 18, 8],
    },
    radii: { atomic: 108, covalent: 140, van_der_waals: 216, ionic: null },
    thermodynamics: {
      melting_point_k: 161.4,
      boiling_point_k: 165.03,
      heat_of_fusion_kj_mol: 2.27,
      heat_of_vaporization_kj_mol: 12.64,
      specific_heat_j_gk: 0.158,
      thermal_conductivity_w_mk: 0.00565,
    },
    electrical: {
      electronegativity_pauling: 2.6,
      ionization_energies_kj_mol: [1170.4, 2046.4, 3099.4],
      electron_affinity_kj_mol: 0,
      electrical_conductivity_s_m: null,
      magnetic_type: "diamagnetic",
    },
    abundance: {
      earth_crust_ppm: 0.000002,
      ocean_ppm: 0.0001,
      universe_ppm: 0.004,
      human_body_ppm: null,
    },
    isotopes: [
      { mass_number: 124, natural_abundance_percent: 0.09, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 126, natural_abundance_percent: 0.09, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 128, natural_abundance_percent: 1.92, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 129, natural_abundance_percent: 26.44, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 130, natural_abundance_percent: 4.08, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 131, natural_abundance_percent: 21.18, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 132, natural_abundance_percent: 26.89, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 134, natural_abundance_percent: 10.44, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 136, natural_abundance_percent: 8.87, half_life: ">2.17×10²¹ yr", decay_mode: "β−β−", is_stable: false },
    ],
    radioactive: false,
    stability: "stable",
    discovery: {
      discoverer: "William Ramsay / Morris Travers",
      year: 1898,
      location: "England",
      named_after: "Greek: xenos (stranger)",
      etymology: "The strange element",
    },
    cas_number: "7440-63-3",
    description: "A noble gas forming true chemical compounds with fluorine and oxygen; used as a general anesthetic and in ion propulsion systems for spacecraft.",
    detailed_description: "Xenon was historically thought to be completely unreactive, but in 1962 Neil Bartlett synthesized the first noble gas compound, xenon hexafluoroplatinate. Xenon forms numerous stable compounds. It is used as a general anesthetic, in high-intensity arc lamps for cinema projectors, in flash lamps, and as ion propellant in spacecraft thrusters. Xenon-133 is used in nuclear medicine for lung imaging.",
    toxicity_level: "none",
    hazard_codes: ["GHS04"],
  },
  {
    atomic_number: 79,
    name: "Gold",
    symbol: "Au",
    latin_name: "Aurum",
    period: 6,
    group: 11,
    block: "d",
    category: "transition metal",
    phase_at_stp: "solid",
    standard_state_color: "metallic yellow",
    atomic_mass: 196.967,
    density_g_cm3: 19.3,
    valency: [1, 3],
    oxidation_states: [-1, 0, 1, 2, 3, 5],
    common_oxidation_state: 3,
    electronic_configuration: {
      full: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 4f¹⁴ 5s² 5p⁶ 5d¹⁰ 6s¹",
      shorthand: "[Xe] 4f¹⁴ 5d¹⁰ 6s¹",
      noble_gas_core: "Xe",
      valence_electrons: 1,
      electron_shells: [2, 8, 18, 32, 18, 1],
    },
    radii: { atomic: 174, covalent: 136, van_der_waals: 166, ionic: 85 },
    thermodynamics: {
      melting_point_k: 1337.33,
      boiling_point_k: 3129,
      heat_of_fusion_kj_mol: 12.55,
      heat_of_vaporization_kj_mol: 324,
      specific_heat_j_gk: 0.129,
      thermal_conductivity_w_mk: 318,
    },
    electrical: {
      electronegativity_pauling: 2.54,
      ionization_energies_kj_mol: [890.1, 1980],
      electron_affinity_kj_mol: 222.8,
      electrical_conductivity_s_m: 4.52e7,
      magnetic_type: "diamagnetic",
    },
    abundance: {
      earth_crust_ppm: 0.004,
      ocean_ppm: 0.000011,
      universe_ppm: 0.0006,
      human_body_ppm: null,
    },
    isotopes: [
      { mass_number: 197, natural_abundance_percent: 100, half_life: "stable", decay_mode: null, is_stable: true },
    ],
    radioactive: false,
    stability: "stable",
    discovery: {
      discoverer: "Known since antiquity",
      year: null,
      location: null,
      named_after: "Anglo-Saxon: gold; symbol from Latin Aurum",
      etymology: "Ancient name for the precious metal",
    },
    cas_number: "7440-57-5",
    description: "The most malleable metal known; a noble metal that does not corrode, used in jewelry, electronics, and as a monetary standard for millennia.",
    detailed_description: "Gold is one of the least reactive chemical elements. It is a dense, soft, shiny, malleable metal — one ounce can be beaten into 300 square feet of gold leaf. It does not react with oxygen or most acids, only with aqua regia. Gold's resistance to corrosion makes it ideal for electrical connectors and contacts. Its relativistic effects give it its characteristic yellow color and unique chemistry.",
    toxicity_level: "none",
    hazard_codes: [],
  },
  {
    atomic_number: 80,
    name: "Mercury",
    symbol: "Hg",
    latin_name: "Hydrargyrum",
    period: 6,
    group: 12,
    block: "d",
    category: "transition metal",
    phase_at_stp: "liquid",
    standard_state_color: "silver-white metallic liquid",
    atomic_mass: 200.592,
    density_g_cm3: 13.534,
    valency: [1, 2],
    oxidation_states: [0, 1, 2],
    common_oxidation_state: 2,
    electronic_configuration: {
      full: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 4f¹⁴ 5s² 5p⁶ 5d¹⁰ 6s²",
      shorthand: "[Xe] 4f¹⁴ 5d¹⁰ 6s²",
      noble_gas_core: "Xe",
      valence_electrons: 2,
      electron_shells: [2, 8, 18, 32, 18, 2],
    },
    radii: { atomic: 171, covalent: 132, van_der_waals: 155, ionic: 119 },
    thermodynamics: {
      melting_point_k: 234.32,
      boiling_point_k: 629.88,
      heat_of_fusion_kj_mol: 2.29,
      heat_of_vaporization_kj_mol: 59.11,
      specific_heat_j_gk: 0.14,
      thermal_conductivity_w_mk: 8.3,
    },
    electrical: {
      electronegativity_pauling: 2.0,
      ionization_energies_kj_mol: [1007.1, 1810, 3300],
      electron_affinity_kj_mol: 0,
      electrical_conductivity_s_m: 1.04e6,
      magnetic_type: "diamagnetic",
    },
    abundance: {
      earth_crust_ppm: 0.067,
      ocean_ppm: 0.00003,
      universe_ppm: 0.1,
      human_body_ppm: null,
    },
    isotopes: [
      { mass_number: 196, natural_abundance_percent: 0.15, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 198, natural_abundance_percent: 9.97, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 199, natural_abundance_percent: 16.87, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 200, natural_abundance_percent: 23.1, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 201, natural_abundance_percent: 13.18, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 202, natural_abundance_percent: 29.86, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 204, natural_abundance_percent: 6.87, half_life: "stable", decay_mode: null, is_stable: true },
    ],
    radioactive: false,
    stability: "stable",
    discovery: {
      discoverer: "Known since antiquity",
      year: null,
      location: null,
      named_after: "Planet Mercury; symbol from Latin Hydrargyrum (liquid silver)",
      etymology: "From its liquid, silvery appearance",
    },
    cas_number: "7439-97-6",
    description: "The only metal that is liquid at room temperature; highly toxic, especially as methylmercury; historically used in thermometers and dental amalgam.",
    detailed_description: "Mercury is the only metal that is liquid at standard temperature and pressure. Its high density, surface tension, and electrical conductivity have made it useful in thermometers, barometers, and switches. However, mercury and its compounds are highly toxic, causing neurological damage. Methylmercury, produced by microbial activity, bioaccumulates in food chains and was the cause of Minamata disease in Japan.",
    toxicity_level: "extreme",
    hazard_codes: ["GHS06", "GHS08", "GHS09"],
  },
  {
    atomic_number: 82,
    name: "Lead",
    symbol: "Pb",
    latin_name: "Plumbum",
    period: 6,
    group: 14,
    block: "p",
    category: "post-transition metal",
    phase_at_stp: "solid",
    standard_state_color: "bluish-white / gray",
    atomic_mass: 207.2,
    density_g_cm3: 11.34,
    valency: [2, 4],
    oxidation_states: [-4, -2, -1, 0, 1, 2, 3, 4],
    common_oxidation_state: 2,
    electronic_configuration: {
      full: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 4f¹⁴ 5s² 5p⁶ 5d¹⁰ 6s² 6p²",
      shorthand: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²",
      noble_gas_core: "Xe",
      valence_electrons: 4,
      electron_shells: [2, 8, 18, 32, 18, 4],
    },
    radii: { atomic: 175, covalent: 146, van_der_waals: 202, ionic: 119 },
    thermodynamics: {
      melting_point_k: 600.61,
      boiling_point_k: 2022,
      heat_of_fusion_kj_mol: 4.77,
      heat_of_vaporization_kj_mol: 177.8,
      specific_heat_j_gk: 0.128,
      thermal_conductivity_w_mk: 35.3,
    },
    electrical: {
      electronegativity_pauling: 2.33,
      ionization_energies_kj_mol: [715.6, 1450.5, 3081.5],
      electron_affinity_kj_mol: 35.1,
      electrical_conductivity_s_m: 4.55e6,
      magnetic_type: "diamagnetic",
    },
    abundance: {
      earth_crust_ppm: 14,
      ocean_ppm: 0.00003,
      universe_ppm: 0.1,
      human_body_ppm: 0.17,
    },
    isotopes: [
      { mass_number: 204, natural_abundance_percent: 1.4, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 206, natural_abundance_percent: 24.1, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 207, natural_abundance_percent: 22.1, half_life: "stable", decay_mode: null, is_stable: true },
      { mass_number: 208, natural_abundance_percent: 52.4, half_life: "stable", decay_mode: null, is_stable: true },
    ],
    radioactive: false,
    stability: "stable",
    discovery: {
      discoverer: "Known since antiquity",
      year: null,
      location: null,
      named_after: "Anglo-Saxon: lead; symbol from Latin Plumbum",
      etymology: "Ancient metal, origin of 'plumber'",
    },
    cas_number: "7439-92-1",
    description: "A heavy, toxic post-transition metal; historically used in plumbing, paint, and fuel; now primarily used in lead-acid batteries.",
    detailed_description: "Lead is a soft, dense metal that has been used for thousands of years. Its low melting point and malleability made it valuable for plumbing (hence 'plumber' from plumbum), paint pigments, and as an anti-knock additive in gasoline. However, lead is highly toxic and causes irreversible neurological damage, particularly in children. Its major current use is in lead-acid batteries and radiation shielding.",
    toxicity_level: "high",
    hazard_codes: ["GHS06", "GHS08", "GHS09"],
  },
  {
    atomic_number: 92,
    name: "Uranium",
    symbol: "U",
    latin_name: "Uranium",
    period: 7,
    group: null,
    block: "f",
    category: "actinide",
    phase_at_stp: "solid",
    standard_state_color: "silvery-white",
    atomic_mass: 238.029,
    density_g_cm3: 19.1,
    valency: [3, 4, 5, 6],
    oxidation_states: [0, 1, 2, 3, 4, 5, 6],
    common_oxidation_state: 6,
    electronic_configuration: {
      full: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 4f¹⁴ 5s² 5p⁶ 5d¹⁰ 5f³ 6s² 6p⁶ 6d¹ 7s²",
      shorthand: "[Rn] 5f³ 6d¹ 7s²",
      noble_gas_core: "Rn",
      valence_electrons: 6,
      electron_shells: [2, 8, 18, 32, 21, 9, 2],
    },
    radii: { atomic: 196, covalent: 170, van_der_waals: 186, ionic: 103 },
    thermodynamics: {
      melting_point_k: 1405.3,
      boiling_point_k: 4404,
      heat_of_fusion_kj_mol: 9.14,
      heat_of_vaporization_kj_mol: 417.1,
      specific_heat_j_gk: 0.116,
      thermal_conductivity_w_mk: 27.5,
    },
    electrical: {
      electronegativity_pauling: 1.38,
      ionization_energies_kj_mol: [597.6, 1420],
      electron_affinity_kj_mol: 50.94,
      electrical_conductivity_s_m: 3.6e6,
      magnetic_type: "paramagnetic",
    },
    abundance: {
      earth_crust_ppm: 2.7,
      ocean_ppm: 0.0033,
      universe_ppm: 0.0002,
      human_body_ppm: null,
    },
    isotopes: [
      { mass_number: 234, natural_abundance_percent: 0.005, half_life: "245,500 yr", decay_mode: "α", is_stable: false },
      { mass_number: 235, natural_abundance_percent: 0.72, half_life: "703.8×10⁶ yr", decay_mode: "α", is_stable: false },
      { mass_number: 238, natural_abundance_percent: 99.27, half_life: "4.468×10⁹ yr", decay_mode: "α", is_stable: false },
    ],
    radioactive: true,
    stability: "unstable",
    half_life: "4.468×10⁹ yr (U-238)",
    discovery: {
      discoverer: "Martin Heinrich Klaproth",
      year: 1789,
      location: "Germany",
      named_after: "Planet Uranus",
      etymology: "Discovered shortly after planet Uranus was found",
    },
    cas_number: "7440-61-1",
    description: "A naturally radioactive heavy metal; the primary fuel for nuclear power plants and the material used in the first atomic bombs.",
    detailed_description: "Uranium is a naturally occurring radioactive actinide metal with the highest atomic number of all naturally abundant elements. Its two primary isotopes, U-235 (fissile) and U-238, are the basis of both nuclear weapons and nuclear power. Uranium-235 undergoes nuclear fission when struck by slow neutrons, releasing enormous energy. Depleted uranium (mostly U-238) is used in armor-piercing munitions and radiation shielding.",
    toxicity_level: "high",
    hazard_codes: ["GHS06", "GHS08", "GHS09"],
  },
  {
    atomic_number: 94,
    name: "Plutonium",
    symbol: "Pu",
    latin_name: "Plutonium",
    period: 7,
    group: null,
    block: "f",
    category: "actinide",
    phase_at_stp: "solid",
    standard_state_color: "silvery metallic",
    atomic_mass: 244,
    density_g_cm3: 19.816,
    valency: [3, 4, 5, 6],
    oxidation_states: [0, 2, 3, 4, 5, 6, 7, 8],
    common_oxidation_state: 4,
    electronic_configuration: {
      full: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 4f¹⁴ 5s² 5p⁶ 5d¹⁰ 5f⁶ 6s² 6p⁶ 7s²",
      shorthand: "[Rn] 5f⁶ 7s²",
      noble_gas_core: "Rn",
      valence_electrons: 8,
      electron_shells: [2, 8, 18, 32, 24, 8, 2],
    },
    radii: { atomic: 159, covalent: 187, van_der_waals: null, ionic: 100 },
    thermodynamics: {
      melting_point_k: 912.5,
      boiling_point_k: 3505,
      heat_of_fusion_kj_mol: 2.82,
      heat_of_vaporization_kj_mol: 333.5,
      specific_heat_j_gk: 0.13,
      thermal_conductivity_w_mk: 6.74,
    },
    electrical: {
      electronegativity_pauling: 1.28,
      ionization_energies_kj_mol: [584.7],
      electron_affinity_kj_mol: null,
      electrical_conductivity_s_m: 6.7e5,
      magnetic_type: "paramagnetic",
    },
    abundance: {
      earth_crust_ppm: 0,
      ocean_ppm: null,
      universe_ppm: 0,
      human_body_ppm: null,
    },
    isotopes: [
      { mass_number: 238, natural_abundance_percent: 0, half_life: "87.7 yr", decay_mode: "α", is_stable: false },
      { mass_number: 239, natural_abundance_percent: 0, half_life: "24,110 yr", decay_mode: "α", is_stable: false },
      { mass_number: 240, natural_abundance_percent: 0, half_life: "6,564 yr", decay_mode: "α", is_stable: false },
      { mass_number: 244, natural_abundance_percent: 0, half_life: "80.8×10⁶ yr", decay_mode: "α", is_stable: false },
    ],
    radioactive: true,
    stability: "unstable",
    half_life: "24,110 yr (Pu-239)",
    discovery: {
      discoverer: "Glenn T. Seaborg et al.",
      year: 1940,
      location: "USA",
      named_after: "Planet Pluto (then considered a planet)",
      etymology: "Follows uranium (Uranus) and neptunium (Neptune)",
      synthesis_method: "Neutron bombardment of uranium-238 in a cyclotron, producing neptunium-238 which decays to Pu-238",
    },
    cas_number: "7440-07-5",
    description: "A synthetic transuranic radioactive metal produced in nuclear reactors; the primary fissile material in nuclear weapons.",
    detailed_description: "Plutonium is a synthetic element produced by neutron capture in nuclear reactors. Plutonium-239 is fissile and is the primary material in nuclear weapons; the bomb dropped on Nagasaki used Pu-239. It is also used as fuel in some nuclear reactors and in radioisotope thermoelectric generators (RTGs) for spacecraft. Plutonium is extraordinarily toxic by inhalation and is one of the most carefully controlled materials on Earth.",
    toxicity_level: "extreme",
    hazard_codes: ["GHS06", "GHS08"],
  },
  {
    atomic_number: 118,
    name: "Oganesson",
    symbol: "Og",
    latin_name: "Oganesson",
    period: 7,
    group: 18,
    block: "p",
    category: "noble gas",
    phase_at_stp: "unknown",
    standard_state_color: "unknown",
    atomic_mass: 294,
    density_g_cm3: null,
    valency: [0],
    oxidation_states: [0],
    common_oxidation_state: 0,
    electronic_configuration: {
      full: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 4f¹⁴ 5s² 5p⁶ 5d¹⁰ 5f¹⁴ 6s² 6p⁶ 6d¹⁰ 7s² 7p⁶",
      shorthand: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶",
      noble_gas_core: "Rn",
      valence_electrons: 8,
      electron_shells: [2, 8, 18, 32, 32, 18, 8],
    },
    radii: { atomic: 152, covalent: 157, van_der_waals: null, ionic: null },
    thermodynamics: {
      melting_point_k: null,
      boiling_point_k: null,
      heat_of_fusion_kj_mol: null,
      heat_of_vaporization_kj_mol: null,
      specific_heat_j_gk: null,
      thermal_conductivity_w_mk: null,
    },
    electrical: {
      electronegativity_pauling: null,
      ionization_energies_kj_mol: [839.4],
      electron_affinity_kj_mol: null,
      electrical_conductivity_s_m: null,
      magnetic_type: null,
    },    abundance: {
      earth_crust_ppm: 0,
      ocean_ppm: null,
      universe_ppm: 0,
      human_body_ppm: null,
    },
    isotopes: [
      { mass_number: 294, natural_abundance_percent: 0, half_life: "~0.7 ms", decay_mode: "α", is_stable: false },
    ],
    radioactive: true,
    stability: "unstable",
    half_life: "~0.7 ms (Og-294)",
    discovery: {
      discoverer: "Joint Institute for Nuclear Research / Lawrence Livermore National Laboratory",
      year: 2002,
      location: "Russia / USA",
      named_after: "Yuri Oganessian, nuclear physicist",
      etymology: "Named in honor of Professor Yuri Oganessian",
      synthesis_method: "Bombardment of californium-249 with calcium-48 ions in a cyclotron",
    },
    cas_number: "54144-19-3",
    description: "The heaviest known element, a synthetic superheavy noble gas with an extremely short half-life; only a few atoms have ever been created.",
    detailed_description: "Oganesson is a synthetic chemical element and the heaviest known element. It is the only synthetic element classified as a noble gas, though theoretical calculations suggest it may not actually behave as one due to relativistic effects. Only a handful of atoms of oganesson have been synthesized. Its properties are largely unknown and most values are theoretical predictions. It decays almost instantly into lighter elements through alpha decay.",
    toxicity_level: "unknown",
    hazard_codes: ["GHS08"],
  },
// Elements 21-25, 27-28, 31-35, 37-46, 48-52, 55-78, 81, 83-91, 93, 95-117
// follow identical schema structure. A production seed should include all 118.
// Full scientific data available from: https://www.ptable.com, https://webelements.com
// NIST Atomic Spectra Database: https://physics.nist.gov/asd
] as const;
